/**
 * @fileoverview info-list —— 信息列表：一块摆 N 行，每行由「前导列 ｜ 最多三段
 * 左右分列的 line ｜ 尾列」声明式编排，外加一条有值才出的扩展指标行。
 * 参考仓那八个各写一遍的列表类模块收敛成本模块的八套预设，见
 * docs/MODULE_INFO_CARD_DESIGN.md。
 *
 * ⚠ 类型 id 是 `info-list` 而不是 `list`：守「零模块类型字面量」的那道闸按已注册
 * 的 type 逐个 grep 源码，`list` 这种常见词会红在一堆与模块毫不相干的属性上。
 */
import { defineModule } from '../../registry'
import { scrollConfigFields } from '../../shared/scroll'
import {
  LIST_ALARM_ONS,
  LIST_BADGE_KINDS,
  LIST_BADGE_STYLES,
  LIST_DIVIDER_STYLES,
  LIST_GROUPINGS,
  LIST_HOVERS,
  LIST_LABEL_TONES,
  LIST_LEADS,
  LIST_METER_KINDS,
  LIST_METER_SOURCE2S,
  LIST_METER_SOURCES,
  LIST_ROW_FILTERS,
  LIST_ROW_LAYOUTS,
  LIST_ROW_SHELLS,
  LIST_ROW_SORTS,
  LIST_SEGMENTS,
  LIST_SUB_SOURCES,
  LIST_TAILS,
  LIST_TIME_SOURCES,
  LIST_UNIT_PLACES,
} from './options'
import { INFO_LIST_PRESETS } from './presets'
import {
  LIST_ITEMS_KEY,
  LIST_SLOT_KEY,
  listRowCounts,
  listRowLabels,
  readListItems,
} from './rows'
import { valueRulesField } from './rules'

function validateInfoListConfig(config: Record<string, unknown>): string[] {
  const issues: string[] = []
  if (config.alarmOn === 'sub' && config.subSource === 'text') {
    issues.push('规则判定不能使用文本型副读数，请选择数值副读数或主读数')
  }
  if (
    config.timeSource === 'alarmSince' &&
    config.rowFilter !== 'hit' &&
    config.rowFilter !== 'alarm'
  ) {
    issues.push('告警起始时刻仅适用于“命中规则”或“只看告警”筛选')
  }
  return issues
}

export default defineModule({
  type: 'info-list',
  description:
    '信息列表用于纵向呈现固定实体及其主值、副值、状态、进度和扩展指标；单值 KPI 可选信息卡片，动态消息流可选信息流。数据通过 listValues 数组绑定，第 i 行对应 items 第 i 项，并提供数值、文本、状态与扩展子槽。行结构、筛选、分组和告警规则可组合配置；删除或调整 items 顺序会改变后续绑定索引。',
  displayName: '信息列表',
  category: '数据',
  icon: 'table',
  keywords: [
    'infolist',
    'liebiao',
    'xinxi',
    '信息列表',
    '列表',
    '表格',
    '告警',
    '工单',
    '排行',
  ],
  defaultSize: { width: 360, height: 420, minWidth: 160, minHeight: 96 },
  validateConfig: validateInfoListConfig,
  configPresets: INFO_LIST_PRESETS,
  contentKeys: [
    'title',
    LIST_ITEMS_KEY,
    'noRowsText',
    'columnHeader',
    'defaultGroup',
    'subSource',
    'subLabel',
    'badge',
    'meter',
    'extras',
    'rules',
    'alarmOn',
    'rowFilter',
    'rowSort',
    'holdSeconds',
    'calmText',
    'timeSource',
  ],
  configSchema: [
    {
      key: 'title',
      label: '标题',
      type: 'string',
      group: '内容',
      default: '',
      span: 'full',
      placeholder: '留空则隐藏标题栏',
    },
    {
      key: LIST_ITEMS_KEY,
      label: '行',
      type: 'array',
      group: '内容',
      help: '每项对应一个绑定行。删除中间项会使后续绑定索引前移，操作后请复核绑定。',
      itemLabelKey: 'label',
      minItems: 1,
      // ⚠ 出厂给一项：空列表时模块是一块什么都没有的白板，而属性面板上
      //   「新增一行」不在最显眼的位置，看着像模块坏了
      default: [{ label: '点位 1', unit: '', precision: 1 }],
      span: 'full',
      itemSchema: [
        {
          key: 'label',
          label: '行名',
          type: 'string',
          default: '',
          placeholder: '留空显示「点位 N」',
        },
        {
          key: 'unit',
          label: '单位',
          type: 'string',
          default: '',
          placeholder: '例如：℃ / kWh / m³/h',
          // ⚠ 不去首尾空格：「° C」这类带空格是用户显式的排版意图
          help: '保留首尾空格，可用于控制单位与读数的间距。',
        },
        {
          key: 'precision',
          label: '小数位',
          type: 'range',
          default: 1,
          min: 0,
          max: 6,
          step: 1,
        },
        {
          key: 'tag',
          label: '分类标签',
          type: 'string',
          default: '',
          help: '在行内显示分类标签，文字跟随当前行颜色；可与状态徽章同时显示。',
        },
        {
          key: 'group',
          label: '分组',
          type: 'string',
          default: '',
          help: '指定分段或页签归属。留空时在分段模式归入“其它”，在页签模式仅显示于“全部”。',
        },
        {
          key: 'color',
          label: '固定颜色',
          type: 'color',
          default: '',
          help: '设置当前行的固定颜色，优先级高于规则颜色，适用于能源类型等静态分类。建议填写 var(--…) 主题变量，固定色值不会随主题切换。',
        },
        {
          key: 'icon',
          label: '行首图标',
          type: 'image',
          default: '',
          help: '选择「图标」作为前导列时显示素材库图标；素材不可用时显示圆点。',
        },
        {
          key: 'range',
          label: '量程',
          type: 'object',
          // ⚠ 三个子键刻意都不给 default：留空 = 不画目标标记、不算完成率。
          //   给 0 会让「没填」与「真的是 0」在算式里再也分不开
          help: '设置「量程占比」进度条的上下界与目标值；留空时不计算对应项。',
          fields: [
            { key: 'min', label: '下限', type: 'number' },
            { key: 'max', label: '上限', type: 'number' },
            { key: 'target', label: '目标值', type: 'number' },
          ],
        },
        {
          key: 'desc',
          label: '描述',
          type: 'string',
          default: '',
          help: '设置行内描述；已绑定描述子槽时优先使用绑定值，此处作为默认内容。',
        },
        {
          key: 'emitValue',
          label: '联动值',
          type: 'string',
          default: '',
          help: '点击行时发送的联动值；留空则不发送行级事件。',
        },
      ],
    },
    {
      key: 'noRowsText',
      label: '无行占位',
      type: 'string',
      group: '内容',
      default: '暂无数据',
      span: 'half',
      help: '未配置任何行时显示。',
    },
    {
      key: 'rowLayout',
      label: '排版',
      type: 'enum',
      group: '行结构',
      default: 'stack',
      span: 'half',
      help: '三列表模式不使用「行编排」与「前导 / 尾列」，固定显示名称、数值和单位三列。',
      options: [...LIST_ROW_LAYOUTS],
    },
    {
      key: 'rowLines',
      label: '行编排',
      type: 'array',
      group: '行结构',
      maxItems: 3,
      itemLabelKey: 'left',
      span: 'full',
      when: { key: 'rowLayout', in: ['stack'] },
      help: '每行最多显示三段，各段分为左右两组并分别对齐；内容均为空的段不显示。',
      default: [
        { left: 'label', left2: 'none', right: 'value', right2: 'none' },
      ],
      itemSchema: [
        {
          key: 'left',
          label: '左 1',
          type: 'enum',
          default: 'none',
          options: [...LIST_SEGMENTS],
        },
        {
          key: 'left2',
          label: '左 2',
          type: 'enum',
          default: 'none',
          options: [...LIST_SEGMENTS],
        },
        {
          key: 'right',
          label: '右 1',
          type: 'enum',
          default: 'none',
          options: [...LIST_SEGMENTS],
        },
        {
          key: 'right2',
          label: '右 2',
          type: 'enum',
          default: 'none',
          options: [...LIST_SEGMENTS],
        },
      ],
    },
    {
      key: 'rowShape',
      label: '前导与尾列',
      type: 'object',
      group: '行结构',
      span: 'full',
      when: { key: 'rowLayout', in: ['stack'] },
      help: '前导列与两个尾列都垂直居中、跨全部行段。',
      default: { lead: 'none', tail: 'none', tail2: 'none', extras: false },
      fields: [
        {
          key: 'lead',
          label: '前导列',
          type: 'enum',
          default: 'none',
          options: [...LIST_LEADS],
        },
        {
          key: 'tail',
          label: '尾列 1',
          type: 'enum',
          default: 'none',
          options: [...LIST_TAILS],
        },
        {
          key: 'tail2',
          label: '尾列 2',
          type: 'enum',
          default: 'none',
          options: [...LIST_TAILS],
        },
        {
          key: 'extras',
          label: '扩展指标行',
          type: 'boolean',
          default: false,
          help: '在行段下方显示扩展指标；仅展示「扩展指标」中已配置且有值的项目。',
        },
      ],
    },
    {
      key: 'columnHeader',
      label: '表头',
      type: 'object',
      group: '表头',
      span: 'full',
      when: { key: 'rowLayout', in: ['columns'] },
      default: { show: true, name: '名称', value: '数值', unit: '单位' },
      fields: [
        { key: 'show', label: '显示表头', type: 'boolean', default: true },
        {
          key: 'name',
          label: '名称列',
          type: 'string',
          default: '名称',
          when: { key: 'show', in: [true] },
        },
        {
          key: 'value',
          label: '数值列',
          type: 'string',
          default: '数值',
          when: { key: 'show', in: [true] },
        },
        {
          key: 'unit',
          label: '单位列',
          type: 'string',
          default: '单位',
          when: { key: 'show', in: [true] },
        },
      ],
    },
    {
      key: 'spacing',
      label: '间距',
      type: 'object',
      group: '间距',
      span: 'full',
      default: { padX: 6, padY: 4, rowPadX: 4, rowPadY: 6 },
      fields: [
        {
          key: 'padX',
          label: '模块水平内边距 (px)',
          type: 'range',
          default: 6,
          min: 0,
          max: 40,
          step: 1,
        },
        {
          key: 'padY',
          label: '模块垂直内边距 (px)',
          type: 'range',
          default: 4,
          min: 0,
          max: 40,
          step: 1,
        },
        {
          key: 'rowPadX',
          label: '行左右内边距 (px)',
          type: 'range',
          default: 4,
          min: 0,
          max: 40,
          step: 1,
        },
        {
          key: 'rowPadY',
          label: '行上下内边距 (px)',
          type: 'range',
          default: 6,
          min: 0,
          max: 40,
          step: 1,
        },
      ],
    },
    {
      key: 'rowShell',
      label: '行外壳',
      type: 'enum',
      group: '外壳',
      default: 'divider',
      span: 'half',
      help: '告警状态以描边和呼吸效果叠加在外壳上，不会替换此处选择的外壳样式。',
      options: [...LIST_ROW_SHELLS],
    },
    {
      key: 'dividerStyle',
      label: '分隔线',
      type: 'enum',
      group: '外壳',
      default: 'dotted',
      span: 'half',
      options: [...LIST_DIVIDER_STYLES],
    },
    {
      key: 'hover',
      label: '悬停反馈',
      type: 'enum',
      group: '外壳',
      default: 'none',
      span: 'half',
      help: '触摸设备不支持悬停，建议同时配置适用于触摸操作的反馈方式。',
      options: [...LIST_HOVERS],
    },
    ...scrollConfigFields(),
    {
      key: 'grouping',
      label: '分组',
      type: 'enum',
      group: '分组',
      default: 'none',
      span: 'half',
      help: '按行内「分组」值进行分段或分页签；页签计数使用全部行数，而非当前页签子集。',
      options: [...LIST_GROUPINGS],
    },
    {
      key: 'defaultGroup',
      label: '初始分组',
      type: 'string',
      group: '分组',
      default: '',
      span: 'half',
      when: { key: 'grouping', in: ['tabs'] },
      placeholder: '留空时显示全部分组',
      help: '页签模式的默认选项；用户手动切换后以当前选择为准。',
    },
    {
      key: 'labelSize',
      label: '行名字号 (px)',
      type: 'range',
      group: '标签',
      default: 13,
      min: 8,
      max: 48,
      step: 1,
      span: 'half',
    },
    {
      key: 'labelTone',
      label: '行名文字色',
      type: 'enum',
      group: '标签',
      default: 'secondary',
      span: 'half',
      options: [...LIST_LABEL_TONES],
    },
    {
      key: 'valueSize',
      label: '读数字号 (px)',
      type: 'range',
      group: '数值',
      default: 16,
      min: 8,
      max: 96,
      step: 1,
      span: 'half',
    },
    {
      key: 'valueColor',
      label: '读数颜色',
      type: 'color',
      group: '数值',
      // 命中规则的那一行改用规则自己的颜色，这里是没命中时的颜色
      default: 'var(--accent-secondary)',
      span: 'half',
      help: '设置未命中取值规则时的颜色；规则命中后优先使用规则颜色。',
    },
    {
      key: 'valueGlow',
      label: '读数辉光 (px)',
      type: 'range',
      group: '数值',
      default: 0,
      min: 0,
      max: 24,
      step: 1,
      span: 'half',
    },
    {
      key: 'unitPlace',
      label: '单位位置',
      type: 'enum',
      group: '单位',
      default: 'attached',
      span: 'half',
      help: '「独占一列」仅在三列表模式生效；行内编排模式下等同于紧跟读数。',
      options: [...LIST_UNIT_PLACES],
    },
    {
      key: 'unitSize',
      label: '单位字号 (px)',
      type: 'range',
      group: '单位',
      default: 11,
      min: 8,
      max: 32,
      step: 1,
      span: 'half',
    },
    {
      key: 'subSource',
      label: '副读数取值',
      type: 'enum',
      group: '副读数',
      default: 'aux',
      span: 'half',
      help: '与两条进度条的选源相互独立。选择“行内目标值”时，每行都必须配置量程中的目标值。',
      options: [...LIST_SUB_SOURCES],
    },
    {
      key: 'subLabel',
      label: '副读数前缀',
      type: 'string',
      group: '副读数',
      default: '',
      span: 'half',
      placeholder: '例如：目标 / 水温 / 能效',
    },
    {
      key: 'badge',
      label: '状态徽章',
      type: 'object',
      group: '徽章',
      span: 'full',
      default: { kind: 'none', style: 'outline' },
      fields: [
        {
          key: 'kind',
          label: '取值来源',
          type: 'enum',
          default: 'none',
          help: '「严重度」显示正常、提示、警告或危急；「命中规则」显示规则自身文案。',
          options: [...LIST_BADGE_KINDS],
        },
        {
          key: 'style',
          label: '样式',
          type: 'enum',
          default: 'outline',
          when: { key: 'kind', in: ['severity', 'rule'] },
          help: '设备状态使用内置五级配色与呼吸效果，不受此设置影响。',
          options: [...LIST_BADGE_STYLES],
        },
      ],
    },
    {
      key: 'meter',
      label: '进度条',
      type: 'object',
      group: '进度',
      span: 'full',
      help: '两条进度条共用样式设置，仅数据源与前缀分别配置。',
      default: {
        kind: 'none',
        source: 'range',
        label: '',
        height: 4,
        width: 0,
        color: '',
        glow: 6,
        dot: false,
        showPercent: true,
        source2: 'none',
        label2: '',
      },
      fields: [
        {
          key: 'kind',
          label: '样式',
          type: 'enum',
          default: 'none',
          options: [...LIST_METER_KINDS],
        },
        {
          key: 'source',
          label: '第一条数据源',
          type: 'enum',
          default: 'range',
          when: { key: 'kind', in: ['bar'] },
          options: [...LIST_METER_SOURCES],
        },
        {
          key: 'label',
          label: '第一条前缀',
          type: 'string',
          default: '',
          when: { key: 'kind', in: ['bar'] },
        },
        {
          key: 'height',
          label: '条粗 (px)',
          type: 'range',
          default: 4,
          min: 1,
          max: 24,
          step: 1,
          when: { key: 'kind', in: ['bar'] },
        },
        {
          key: 'width',
          label: '条宽 (px)',
          type: 'range',
          default: 0,
          min: 0,
          max: 400,
          step: 1,
          when: { key: 'kind', in: ['bar'] },
          help: '0 表示填满剩余宽度。',
        },
        {
          key: 'color',
          label: '条色',
          type: 'color',
          default: '',
          when: { key: 'kind', in: ['bar'] },
          placeholder: '留空时跟随当前行颜色',
        },
        {
          key: 'glow',
          label: '辉光 (px)',
          type: 'range',
          default: 6,
          min: 0,
          max: 24,
          step: 1,
          when: { key: 'kind', in: ['bar'] },
        },
        {
          key: 'dot',
          label: '发光圆点',
          type: 'boolean',
          default: false,
          when: { key: 'kind', in: ['bar'] },
          help: '在进度条前显示 4px 发光圆点；两条进度条共用此设置。',
        },
        {
          key: 'showPercent',
          label: '显示百分比',
          type: 'boolean',
          default: true,
          when: { key: 'kind', in: ['bar'] },
        },
        {
          key: 'source2',
          label: '第二条数据源',
          type: 'enum',
          default: 'none',
          when: { key: 'kind', in: ['bar'] },
          options: [...LIST_METER_SOURCE2S],
        },
        {
          key: 'label2',
          label: '第二条前缀',
          type: 'string',
          default: '',
          when: {
            key: 'source2',
            in: ['range', 'share', 'aux', 'aux2', 'aux3'],
          },
        },
      ],
    },
    {
      key: 'extras',
      label: '扩展指标',
      type: 'array',
      group: '扩展',
      maxItems: 3,
      itemLabelKey: 'label',
      span: 'full',
      default: [],
      help: '读取三个扩展子槽，仅显示有值的项目（0 视为有效值）；同时需启用「扩展指标行」。',
      itemSchema: [
        { key: 'label', label: '名称', type: 'string', default: '' },
        { key: 'unit', label: '单位', type: 'string', default: '' },
        {
          key: 'precision',
          label: '小数位',
          type: 'range',
          default: 1,
          min: 0,
          max: 6,
          step: 1,
        },
      ],
    },
    {
      key: 'thousands',
      label: '千分位分隔',
      type: 'boolean',
      group: '格式',
      default: true,
      span: 'half',
    },
    { ...valueRulesField('rules', '取值规则'), group: '告警' },
    {
      key: 'alarmOn',
      label: '规则数据源',
      type: 'enum',
      group: '告警',
      default: 'value',
      span: 'half',
      options: [...LIST_ALARM_ONS],
    },
    {
      key: 'rowFilter',
      label: '行筛选',
      type: 'enum',
      group: '告警',
      default: 'all',
      span: 'half',
      options: [...LIST_ROW_FILTERS],
    },
    {
      key: 'rowSort',
      label: '排序方式',
      type: 'enum',
      group: '告警',
      default: 'docOrder',
      span: 'half',
      options: [...LIST_ROW_SORTS],
    },
    {
      key: 'holdSeconds',
      label: '最短持续 (s)',
      type: 'range',
      group: '迟滞',
      default: 0,
      min: 0,
      max: 300,
      step: 1,
      span: 'half',
      when: { key: 'rowFilter', in: ['hit', 'alarm'] },
      help: '设置告警清除后的最短保留时间，避免阈值附近波动导致条目频繁增删；0 表示清除后立即移除。',
    },
    {
      key: 'calmText',
      label: '无告警占位',
      type: 'string',
      group: '迟滞',
      default: '无活动告警',
      span: 'half',
      when: { key: 'rowFilter', in: ['hit', 'alarm'] },
      help: '用于已配置行但无任何匹配结果的情况；「无行占位」仅用于未配置任何行。',
    },
    {
      key: 'timeSource',
      label: '时刻来源',
      type: 'enum',
      group: '时刻',
      default: 'sample',
      span: 'half',
      help: '采样时刻表示最近一帧到达时间；告警起始时刻仅适用于“命中规则”或“只看告警”筛选；绑定文本原样显示 time 子槽。',
      options: [...LIST_TIME_SOURCES],
    },
  ],
  bindings: [
    {
      key: LIST_SLOT_KEY,
      label: '行读数',
      // ⚠ 只影响 static 常量那一档的输入控件，不过滤可选点位
      dataType: 'number',
      isArray: true,
      // 行钉在配置里的行上：行数由配置决定，绑一部分行是常态，空出来的行
      // 不许让其后整体移位（DASHBOARD_DESIGN §4.2）
      isEntityPinned: true,
      // ⚠ 一个子槽都不给 isRequired：配了 10 行先接 3 个是常态，
      //   给了会让整块被判 unbound 并盖上状态浮层，逐行四档白画
      arrayFields: [
        { key: 'value', label: '主读数', dataType: 'number' },
        { key: 'aux', label: '副读数 1 / 判据值', dataType: 'number' },
        { key: 'aux2', label: '副读数 2', dataType: 'number' },
        { key: 'aux3', label: '副读数 3', dataType: 'number' },
        // ⚠ 刻意不声明 enumMap：求值层的 applyEnumMap 会真的把数值换成映射值，
        //   而本仓契约把 enumMap 定义成「数值 → 中文文案」。声明了会让
        //   toDeviceStatus 拿到中文并落到 unknown，全屏徽章集体变灰且不报错。
        //   不声明时数值原样到达，走 shared/status.ts 的数值旁路
        { key: 'status', label: '设备状态', dataType: 'number' },
        { key: 'name', label: '行名', dataType: 'string' },
        { key: 'text', label: '描述', dataType: 'string' },
        { key: 'time', label: '时刻文本', dataType: 'string' },
        { key: 'extra1', label: '扩展 1', dataType: 'number' },
        { key: 'extra2', label: '扩展 2', dataType: 'number' },
        { key: 'extra3', label: '扩展 3', dataType: 'number' },
      ],
    },
  ],
  // 十行里坏掉一行不该让另外九行一起被浮层盖住，四档由模块自己逐行交代
  ownsStatusDisplay: true,
  // 点某一行上抛这一行的联动值（配了联动值的行才抛）
  emitsInteractions: true,
  // 整块可点由宿主接管；行内点击在模板里 `.stop`，否则同一次点击会被兜底再抛一次
  hostClickable: true,
  bindingRowLabels: (config) =>
    listRowLabels(readListItems(config[LIST_ITEMS_KEY])),
  // ⚠ 行不是用户在绑点面板上随手加的：行号就是行的文档序。不声明行数的话，
  //   面板会摆出「新增一行」，加出来的那一行永远喂不到任何东西
  bindingRowCounts: (config) =>
    listRowCounts(readListItems(config[LIST_ITEMS_KEY])),
  preview: {
    config: {
      [LIST_ITEMS_KEY]: [
        { label: '出水温度', unit: '℃', precision: 1 },
        { label: '回水温度', unit: '℃', precision: 1 },
        { label: '瞬时流量', unit: 'm³/h', precision: 1 },
      ],
    },
    values: {
      [LIST_SLOT_KEY]: [{ value: 55.3 }, { value: 42.8 }, { value: 36.5 }],
    },
  },
  component: () => import('./Component.vue'),
})
