/**
 * @fileoverview info-list 的八套配置预设：参考仓那八个各写一遍的列表类模块，
 * 逐值落成这里的八组配置（MODULE_INFO_CARD_DESIGN §1.3）。
 *
 * ⚠ 每套都把「观感」那 32 个键写全，且簇内子键顺序与该字段 `default` 逐字相同。
 * 应用预设是**浅合并**：少写一个键，上一套留在 configJson 里的那个值就原样残留，
 * 而点亮判定做的是子集比较、照样把按钮点亮——既错了又没有任何提示。
 * ⚠ 场景预设会改变告警、筛选与时刻策略，属性面板会在提示中明确说明
 * 内容覆盖风险。`title` / `items` / `noRowsText` 不由预设修改。
 */
import type { ConfigPreset } from '@dt/contracts'

export const INFO_LIST_PRESETS: ConfigPreset[] = [
  {
    id: 'row-list',
    label: '点线行列表',
    hint: '每行显示一个点位，名称左对齐、读数右对齐，并使用点线分隔与自动滚动。',
    config: {
      rowLayout: 'stack',
      rowLines: [
        { left: 'label', left2: 'none', right: 'value', right2: 'none' },
      ],
      rowShape: { lead: 'icon', tail: 'none', tail2: 'none', extras: false },
      columnHeader: { show: false, name: '名称', value: '数值', unit: '单位' },
      spacing: { padX: 6, padY: 4, rowPadX: 4, rowPadY: 6 },
      rowShell: 'divider',
      dividerStyle: 'dotted',
      hover: 'none',
      autoScroll: true,
      scrollSpeed: 3,
      grouping: 'none',
      defaultGroup: '',
      labelSize: 13,
      labelTone: 'secondary',
      valueSize: 16,
      valueColor: 'var(--accent-secondary)',
      valueGlow: 0,
      unitPlace: 'attached',
      unitSize: 11,
      subSource: 'aux',
      subLabel: '',
      badge: { kind: 'none', style: 'outline' },
      meter: {
        kind: 'none',
        source: 'range',
        label: '',
        height: 4,
        width: 0,
        color: '',
        glow: 6,
        dot: false,
        showPercent: true,
        source2: 'none',
        label2: '',
      },
      extras: [],
      thousands: true,
      alarmOn: 'value',
      rowFilter: 'all',
      rowSort: 'docOrder',
      holdSeconds: 0,
      calmText: '无活动告警',
      timeSource: 'sample',
    },
  },
  {
    id: 'three-col',
    label: '三列表',
    hint: '名称、数值与单位三列对齐并显示表头，内容超长时自动滚动。',
    config: {
      rowLayout: 'columns',
      rowLines: [
        { left: 'label', left2: 'none', right: 'value', right2: 'none' },
      ],
      rowShape: { lead: 'none', tail: 'none', tail2: 'none', extras: false },
      columnHeader: { show: true, name: '名称', value: '数值', unit: '单位' },
      spacing: { padX: 8, padY: 4, rowPadX: 4, rowPadY: 6 },
      rowShell: 'divider',
      dividerStyle: 'dotted',
      hover: 'tint',
      autoScroll: true,
      scrollSpeed: 3,
      grouping: 'none',
      defaultGroup: '',
      labelSize: 13,
      labelTone: 'secondary',
      valueSize: 13,
      valueColor: 'var(--accent-secondary)',
      valueGlow: 0,
      unitPlace: 'column',
      // ⚠ 单位列与数值行同字号：列宽由它推算，跟着读数走才不会把单位挤出去
      unitSize: 13,
      subSource: 'aux',
      subLabel: '',
      badge: { kind: 'none', style: 'outline' },
      meter: {
        kind: 'none',
        source: 'range',
        label: '',
        height: 4,
        width: 0,
        color: '',
        glow: 6,
        dot: false,
        showPercent: true,
        source2: 'none',
        label2: '',
      },
      extras: [],
      thousands: true,
      alarmOn: 'value',
      rowFilter: 'all',
      rowSort: 'docOrder',
      holdSeconds: 0,
      calmText: '无活动告警',
      timeSource: 'sample',
    },
  },
  {
    id: 'target-badge-list',
    label: '指标维护表',
    hint: '双行卡片布局：名称与读数位于上方，目标与状态徽章位于下方；状态徽章仅在配置取值规则后显示。',
    config: {
      rowLayout: 'stack',
      rowLines: [
        {
          left: 'label',
          left2: 'none',
          right: 'value',
          right2: 'none',
        },
        { left: 'sub', left2: 'none', right: 'badge', right2: 'none' },
      ],
      rowShape: { lead: 'none', tail: 'none', tail2: 'none', extras: false },
      columnHeader: { show: false, name: '名称', value: '数值', unit: '单位' },
      spacing: { padX: 8, padY: 4, rowPadX: 4, rowPadY: 8 },
      rowShell: 'divider',
      dividerStyle: 'dotted',
      hover: 'none',
      autoScroll: true,
      scrollSpeed: 3,
      grouping: 'none',
      defaultGroup: '',
      labelSize: 14,
      labelTone: 'primary',
      valueSize: 22,
      valueColor: 'var(--accent-secondary)',
      valueGlow: 10,
      unitPlace: 'attached',
      unitSize: 11,
      subSource: 'target',
      subLabel: '目标',
      badge: { kind: 'rule', style: 'outline' },
      meter: {
        kind: 'none',
        source: 'range',
        label: '',
        height: 4,
        width: 0,
        color: '',
        glow: 6,
        dot: false,
        showPercent: true,
        source2: 'none',
        label2: '',
      },
      extras: [],
      thousands: true,
      // 指标的达标线逐块不同，没有一组通用阈值可以出厂预置
      alarmOn: 'value',
      rowFilter: 'all',
      rowSort: 'docOrder',
      holdSeconds: 0,
      calmText: '无活动告警',
      timeSource: 'sample',
    },
  },
  {
    id: 'source-card',
    label: '能源源卡片',
    hint: '依次展示左侧图标、状态徽章、分类标签、占比条与扩展指标行。',
    config: {
      rowLayout: 'stack',
      rowLines: [
        { left: 'label', left2: 'none', right: 'none', right2: 'none' },
        { left: 'badge', left2: 'tag', right: 'value', right2: 'none' },
        { left: 'sub', left2: 'none', right: 'meter', right2: 'none' },
      ],
      rowShape: { lead: 'icon', tail: 'none', tail2: 'none', extras: true },
      columnHeader: { show: false, name: '名称', value: '数值', unit: '单位' },
      spacing: { padX: 6, padY: 4, rowPadX: 9, rowPadY: 5 },
      rowShell: 'accent',
      dividerStyle: 'none',
      hover: 'lift',
      autoScroll: true,
      scrollSpeed: 5,
      grouping: 'none',
      defaultGroup: '',
      labelSize: 13,
      labelTone: 'title',
      valueSize: 18,
      valueColor: 'var(--accent-secondary)',
      valueGlow: 8,
      unitPlace: 'attached',
      unitSize: 11,
      subSource: 'aux',
      subLabel: '能效',
      badge: { kind: 'device', style: 'outline' },
      meter: {
        kind: 'bar',
        source: 'share',
        label: '占比',
        height: 4,
        width: 128,
        color: '',
        glow: 6,
        dot: false,
        showPercent: true,
        source2: 'none',
        label2: '',
      },
      extras: [
        { label: '功率', unit: 'kW', precision: 1 },
        { label: '温度', unit: '℃', precision: 1 },
        { label: '流量', unit: 'm³/h', precision: 1 },
      ],
      thousands: true,
      // 能源类型是静态元数据不是值驱动的：五色走逐行「固定颜色」
      alarmOn: 'value',
      rowFilter: 'all',
      rowSort: 'docOrder',
      holdSeconds: 0,
      calmText: '无活动告警',
      timeSource: 'sample',
    },
  },
  {
    id: 'terminal-card',
    label: '分类末端卡',
    hint: '顶部显示分类页签，行内展示当日读数与固定宽度占比条。',
    config: {
      rowLayout: 'stack',
      rowLines: [
        { left: 'label', left2: 'tag', right: 'badge', right2: 'none' },
        { left: 'value', left2: 'none', right: 'meter', right2: 'none' },
      ],
      rowShape: { lead: 'none', tail: 'none', tail2: 'none', extras: false },
      columnHeader: { show: false, name: '名称', value: '数值', unit: '单位' },
      spacing: { padX: 6, padY: 4, rowPadX: 8, rowPadY: 4 },
      rowShell: 'card',
      dividerStyle: 'none',
      hover: 'tint',
      autoScroll: true,
      scrollSpeed: 4,
      grouping: 'tabs',
      defaultGroup: '',
      labelSize: 12,
      labelTone: 'title',
      valueSize: 17,
      valueColor: 'var(--accent-secondary)',
      valueGlow: 8,
      unitPlace: 'attached',
      unitSize: 11,
      subSource: 'aux',
      subLabel: '',
      badge: { kind: 'device', style: 'outline' },
      meter: {
        kind: 'bar',
        source: 'share',
        label: '占比',
        height: 3,
        width: 50,
        color: '',
        glow: 6,
        dot: false,
        showPercent: true,
        source2: 'none',
        label2: '',
      },
      extras: [],
      thousands: true,
      alarmOn: 'value',
      rowFilter: 'all',
      rowSort: 'docOrder',
      holdSeconds: 0,
      calmText: '无活动告警',
      timeSource: 'sample',
    },
  },
  {
    id: 'vessel-card',
    label: '容器卡片',
    hint: '按类型分段显示组头，行内展示占比与液位两条同构进度条，水温按区间着色。',
    config: {
      rowLayout: 'stack',
      rowLines: [
        {
          left: 'label',
          left2: 'none',
          right: 'value',
          right2: 'none',
        },
        { left: 'meter', left2: 'none', right: 'sub', right2: 'none' },
        { left: 'meter2', left2: 'none', right: 'none', right2: 'none' },
      ],
      rowShape: { lead: 'none', tail: 'none', tail2: 'none', extras: false },
      columnHeader: { show: false, name: '名称', value: '数值', unit: '单位' },
      spacing: { padX: 6, padY: 4, rowPadX: 7, rowPadY: 6 },
      rowShell: 'card',
      dividerStyle: 'none',
      hover: 'tint',
      autoScroll: true,
      scrollSpeed: 4,
      grouping: 'section',
      defaultGroup: '',
      labelSize: 13,
      labelTone: 'title',
      valueSize: 17,
      valueColor: 'var(--accent-secondary)',
      valueGlow: 8,
      unitPlace: 'attached',
      unitSize: 11,
      subSource: 'aux',
      subLabel: '水温',
      badge: { kind: 'none', style: 'outline' },
      meter: {
        kind: 'bar',
        source: 'range',
        label: '占比',
        height: 4,
        width: 0,
        color: '',
        glow: 6,
        dot: true,
        showPercent: true,
        source2: 'aux2',
        label2: '液位',
      },
      extras: [],
      thousands: true,
      // 水温色相梯度：高危在前，求值器按声明序取首个命中
      rules: [
        {
          op: 'gt',
          value: 55,
          level: 'danger',
          color: 'var(--state-danger)',
          label: '高温',
          blink: false,
        },
        {
          op: 'gt',
          value: 45,
          level: 'warning',
          color: 'var(--state-warning)',
          label: '偏热',
          blink: false,
        },
        {
          op: 'lt',
          value: 30,
          level: 'info',
          color: 'var(--state-info)',
          label: '偏冷',
          blink: false,
        },
        {
          op: 'between',
          value: 30,
          value2: 45,
          level: 'normal',
          color: 'var(--accent-secondary)',
          label: '适温',
          blink: false,
        },
      ],
      alarmOn: 'sub',
      rowFilter: 'all',
      rowSort: 'docOrder',
      holdSeconds: 0,
      calmText: '无活动告警',
      timeSource: 'sample',
    },
  },
  {
    id: 'work-order',
    label: '工单条目',
    hint: '使用左侧状态色边与底纹，并显示实心徽章、描述和时间；状态由三条等值规则确定。',
    config: {
      rowLayout: 'stack',
      rowLines: [
        { left: 'label', left2: 'none', right: 'badge', right2: 'none' },
        { left: 'desc', left2: 'none', right: 'none', right2: 'none' },
        { left: 'time', left2: 'none', right: 'none', right2: 'none' },
      ],
      rowShape: { lead: 'none', tail: 'none', tail2: 'none', extras: false },
      columnHeader: { show: false, name: '名称', value: '数值', unit: '单位' },
      spacing: { padX: 6, padY: 4, rowPadX: 8, rowPadY: 9 },
      rowShell: 'edge',
      dividerStyle: 'dotted',
      hover: 'none',
      autoScroll: true,
      scrollSpeed: 3,
      grouping: 'none',
      defaultGroup: '',
      labelSize: 14,
      labelTone: 'primary',
      valueSize: 16,
      valueColor: 'var(--accent-secondary)',
      valueGlow: 0,
      unitPlace: 'attached',
      unitSize: 11,
      subSource: 'aux',
      subLabel: '',
      badge: { kind: 'rule', style: 'solid' },
      meter: {
        kind: 'none',
        source: 'range',
        label: '',
        height: 4,
        width: 0,
        color: '',
        glow: 6,
        dot: false,
        showPercent: true,
        source2: 'none',
        label2: '',
      },
      extras: [],
      thousands: true,
      // ⚠ 三条严重度都填 normal：工单状态不是「正常/预警/危险」，
      //   填高严重度会让每一条待执行工单都把整行点成告警态
      rules: [
        {
          op: 'eq',
          value: 0,
          level: 'normal',
          color: 'var(--state-warning)',
          label: '待执行',
          blink: false,
        },
        {
          op: 'eq',
          value: 1,
          level: 'normal',
          color: 'var(--state-info)',
          label: '执行中',
          blink: false,
        },
        {
          op: 'eq',
          value: 2,
          level: 'normal',
          color: 'var(--state-success)',
          label: '已完成',
          blink: false,
        },
      ],
      alarmOn: 'sub',
      rowFilter: 'all',
      rowSort: 'docOrder',
      holdSeconds: 0,
      calmText: '无活动告警',
      timeSource: 'bound',
    },
  },
  {
    id: 'alarm-rows',
    label: '活动告警',
    hint: '仅显示命中告警的行，按严重度降序排列，并在行首展示严重度圆点与起始时刻。',
    config: {
      rowLayout: 'stack',
      rowLines: [
        { left: 'label', left2: 'none', right: 'none', right2: 'none' },
        { left: 'alarmText', left2: 'none', right: 'none', right2: 'none' },
      ],
      rowShape: { lead: 'badge', tail: 'value', tail2: 'time', extras: false },
      columnHeader: { show: false, name: '名称', value: '数值', unit: '单位' },
      spacing: { padX: 6, padY: 4, rowPadX: 6, rowPadY: 7 },
      rowShell: 'edge',
      dividerStyle: 'dotted',
      hover: 'none',
      autoScroll: true,
      scrollSpeed: 3,
      grouping: 'none',
      defaultGroup: '',
      labelSize: 13,
      labelTone: 'primary',
      valueSize: 15,
      valueColor: 'var(--accent-secondary)',
      valueGlow: 0,
      unitPlace: 'attached',
      unitSize: 11,
      subSource: 'aux',
      subLabel: '',
      badge: { kind: 'severity', style: 'dot' },
      meter: {
        kind: 'none',
        source: 'range',
        label: '',
        height: 4,
        width: 0,
        color: '',
        glow: 6,
        dot: false,
        showPercent: true,
        source2: 'none',
        label2: '',
      },
      extras: [],
      thousands: true,
      // 报警线逐个点位不同，没有一组通用阈值可以出厂预置
      alarmOn: 'value',
      rowFilter: 'alarm',
      rowSort: 'severity',
      holdSeconds: 0,
      calmText: '无活动告警',
      timeSource: 'alarmSince',
    },
  },
]
