-- GYZky 空调原始分钟视图；字段来源：空调开机字段说明.xls。
-- 接入说明见 README.md；仅在现场 EMS SQL Server 执行。
USE [EMS5.2.2];
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
SET LOCK_TIMEOUT 5000;
SET ANSI_NULLS ON;
SET QUOTED_IDENTIFIER ON;

-- Ct 是待现场确认的时间列；保持本地时间原值，不在视图中转 UTC。
IF OBJECT_ID(N'dbo.GYZky', N'U') IS NULL
    THROW 51000, N'源表 dbo.GYZky 不存在。', 1;
IF NOT EXISTS (
    SELECT 1 FROM sys.columns
    WHERE object_id = OBJECT_ID(N'dbo.GYZky') AND name = N'Ct'
      AND system_type_id IN (58, 61, 42) AND is_nullable = 0
)
    THROW 51001, N'请确认 GYZky 时间列为非空 Ct，类型 datetime/smalldatetime/datetime2。', 1;

DECLARE @required TABLE (name sysname PRIMARY KEY);
INSERT INTO @required (name) VALUES
(N'F1'),
(N'F2'),
(N'F5'),
(N'F6'),
(N'F7'),
(N'F8'),
(N'F11'),
(N'F12'),
(N'F13'),
(N'F14'),
(N'F15'),
(N'F16'),
(N'F17'),
(N'F18'),
(N'F19'),
(N'F20'),
(N'F21'),
(N'F24'),
(N'F25'),
(N'F26'),
(N'F27'),
(N'F28'),
(N'F29'),
(N'F30'),
(N'F31'),
(N'F32'),
(N'F33'),
(N'F34'),
(N'F35'),
(N'F36'),
(N'F37'),
(N'F38'),
(N'F39'),
(N'F40'),
(N'F41'),
(N'F42'),
(N'F43'),
(N'F44'),
(N'F45'),
(N'F46'),
(N'F47'),
(N'F50'),
(N'F51'),
(N'F52'),
(N'F53'),
(N'F54'),
(N'F55'),
(N'F56'),
(N'F57'),
(N'F58'),
(N'F59'),
(N'F60'),
(N'F61'),
(N'F62'),
(N'F63'),
(N'F64'),
(N'F65'),
(N'F66'),
(N'F67'),
(N'F68'),
(N'F69'),
(N'F70'),
(N'F71'),
(N'F72'),
(N'F73'),
(N'F74'),
(N'F75'),
(N'F76'),
(N'F77'),
(N'F78'),
(N'F79'),
(N'F80'),
(N'F81'),
(N'F82'),
(N'F83'),
(N'F84'),
(N'F85'),
(N'F86'),
(N'F89'),
(N'F90'),
(N'F91'),
(N'F92'),
(N'F93'),
(N'F94'),
(N'F95'),
(N'F96'),
(N'F97'),
(N'F98'),
(N'F99'),
(N'F102'),
(N'F103'),
(N'F104'),
(N'F105'),
(N'F106'),
(N'F107'),
(N'F108'),
(N'F109'),
(N'F110'),
(N'F111'),
(N'F112'),
(N'F113'),
(N'F114'),
(N'F115'),
(N'F116'),
(N'F117'),
(N'F118'),
(N'F119'),
(N'F120'),
(N'F121'),
(N'F122'),
(N'F123'),
(N'F124'),
(N'F125'),
(N'F128'),
(N'F129'),
(N'F130'),
(N'F131'),
(N'F132'),
(N'F133'),
(N'F134'),
(N'F135'),
(N'F136'),
(N'F137'),
(N'F138'),
(N'F139'),
(N'F140'),
(N'F141'),
(N'F142'),
(N'F143'),
(N'F144'),
(N'F145'),
(N'F146'),
(N'F147'),
(N'F148'),
(N'F149'),
(N'F150'),
(N'F151'),
(N'F154'),
(N'F155'),
(N'F156'),
(N'F157'),
(N'F158'),
(N'F159'),
(N'F160'),
(N'F161'),
(N'F162'),
(N'F163'),
(N'F164'),
(N'F165'),
(N'F166'),
(N'F167'),
(N'F168'),
(N'F169'),
(N'F170'),
(N'F171'),
(N'F172'),
(N'F173'),
(N'F174'),
(N'F175'),
(N'F176'),
(N'F177'),
(N'F180'),
(N'F181'),
(N'F182'),
(N'F183'),
(N'F184'),
(N'F185'),
(N'F186'),
(N'F187'),
(N'F188'),
(N'F189'),
(N'F190'),
(N'F191'),
(N'F192'),
(N'F193'),
(N'F194'),
(N'F195'),
(N'F196'),
(N'F197'),
(N'F198'),
(N'F199'),
(N'F200'),
(N'F201'),
(N'F202'),
(N'F203'),
(N'F206'),
(N'F207'),
(N'F208'),
(N'F209'),
(N'F210'),
(N'F211'),
(N'F212'),
(N'F213'),
(N'F214'),
(N'F215'),
(N'F216'),
(N'F219'),
(N'F220'),
(N'F221'),
(N'F222'),
(N'F223'),
(N'F224'),
(N'F225'),
(N'F226'),
(N'F227'),
(N'F228'),
(N'F229'),
(N'F230'),
(N'F231'),
(N'F232'),
(N'F233'),
(N'F234'),
(N'F235'),
(N'F236'),
(N'F237'),
(N'F238'),
(N'F239'),
(N'F240'),
(N'F241'),
(N'F242'),
(N'F245'),
(N'F246'),
(N'F247'),
(N'F248'),
(N'F249'),
(N'F250'),
(N'F251'),
(N'F252'),
(N'F253'),
(N'F254'),
(N'F255'),
(N'F256'),
(N'F257'),
(N'F258'),
(N'F259'),
(N'F260'),
(N'F261'),
(N'F262'),
(N'F263'),
(N'F264'),
(N'F265'),
(N'F266'),
(N'F267'),
(N'F268'),
(N'F269'),
(N'F270'),
(N'F271'),
(N'F272'),
(N'F273');
IF EXISTS (
    SELECT 1 FROM @required AS r
    LEFT JOIN sys.columns AS c
      ON c.object_id = OBJECT_ID(N'dbo.GYZky') AND c.name = r.name
    WHERE c.column_id IS NULL OR c.system_type_id NOT IN (48, 52, 56, 59, 60, 62, 104, 106, 108, 122, 127)
)
    THROW 51002, N'源表缺少所需 F 列或列不是数值类型，请核对字段说明。', 1;

DECLARE @views TABLE (name sysname PRIMARY KEY);
INSERT INTO @views (name) VALUES
(N'KTStartData_K01'),
(N'KTStartData_K02'),
(N'KTStartData_K03'),
(N'KTStartData_K04'),
(N'KTStartData_K05'),
(N'KTStartData_K06'),
(N'KTStartData_K07'),
(N'KTStartData_K08'),
(N'KTStartData_K09'),
(N'KTStartData_K10'),
(N'KTStartData_K11'),
(N'KTStartData_K12'),
(N'KTStartData_K13'),
(N'KTStartData_K14'),
(N'KTStartData_K15'),
(N'KTStartData_K16'),
(N'KTStartData_K17'),
(N'KTStartData_K20'),
(N'KTStartData_K21'),
(N'KTStartData_K22'),
(N'KTStartData_K25');
IF EXISTS (
    SELECT 1 FROM @views
    WHERE OBJECT_ID(N'dbo.' + QUOTENAME(name)) IS NOT NULL
)
    THROW 51003, N'存在同名对象；未覆盖，请先核对已有视图定义。', 1;

BEGIN TRY
    BEGIN TRANSACTION;

    EXEC sys.sp_executesql N'CREATE VIEW [dbo].[KTStartData_K01] AS
SELECT
    [Ct] AS [CT],
    CAST([F5] AS float) AS [workshop_temp_avg],
    CAST([F6] AS float) AS [workshop_humidity_avg],
    CAST([F7] AS float) AS [ac_temp_setpoint],
    CAST([F8] AS float) AS [ac_humidity_setpoint],
    CAST([F35] AS float) AS [fresh_air_temp],
    CAST([F36] AS float) AS [fresh_air_humidity],
    CAST([F11] AS float) AS [supply_air_temp],
    CAST([F12] AS float) AS [supply_air_humidity],
    CAST([F13] AS float) AS [return_air_temp],
    CAST([F14] AS float) AS [return_air_humidity],
    CAST([F15] AS float) AS [mixed_air_temp],
    CAST([F16] AS float) AS [mixed_air_humidity],
    CAST([F1] AS float) AS [chilled_water_supply_temp],
    CAST([F2] AS float) AS [chilled_water_supply_pressure],
    CAST(NULL AS float) AS [heat_steam_temp],
    CAST(NULL AS float) AS [heat_steam_pressure],
    CAST(NULL AS float) AS [humidify_steam_temp],
    CAST(NULL AS float) AS [humidify_steam_pressure],
    CAST([F17] AS float) AS [fan_frequency]
FROM [dbo].[GYZky];';

    EXEC sys.sp_executesql N'CREATE VIEW [dbo].[KTStartData_K02] AS
SELECT
    [Ct] AS [CT],
    CAST([F18] AS float) AS [workshop_temp_avg],
    CAST([F19] AS float) AS [workshop_humidity_avg],
    CAST([F20] AS float) AS [ac_temp_setpoint],
    CAST([F21] AS float) AS [ac_humidity_setpoint],
    CAST([F74] AS float) AS [fresh_air_temp],
    CAST([F75] AS float) AS [fresh_air_humidity],
    CAST([F24] AS float) AS [supply_air_temp],
    CAST([F25] AS float) AS [supply_air_humidity],
    CAST([F26] AS float) AS [return_air_temp],
    CAST([F27] AS float) AS [return_air_humidity],
    CAST([F28] AS float) AS [mixed_air_temp],
    CAST([F29] AS float) AS [mixed_air_humidity],
    CAST([F1] AS float) AS [chilled_water_supply_temp],
    CAST([F2] AS float) AS [chilled_water_supply_pressure],
    CAST(NULL AS float) AS [heat_steam_temp],
    CAST(NULL AS float) AS [heat_steam_pressure],
    CAST(NULL AS float) AS [humidify_steam_temp],
    CAST(NULL AS float) AS [humidify_steam_pressure],
    CAST([F30] AS float) AS [fan_frequency]
FROM [dbo].[GYZky];';

    EXEC sys.sp_executesql N'CREATE VIEW [dbo].[KTStartData_K03] AS
SELECT
    [Ct] AS [CT],
    CAST([F31] AS float) AS [workshop_temp_avg],
    CAST([F32] AS float) AS [workshop_humidity_avg],
    CAST([F33] AS float) AS [ac_temp_setpoint],
    CAST([F34] AS float) AS [ac_humidity_setpoint],
    CAST([F35] AS float) AS [fresh_air_temp],
    CAST([F36] AS float) AS [fresh_air_humidity],
    CAST([F37] AS float) AS [supply_air_temp],
    CAST([F38] AS float) AS [supply_air_humidity],
    CAST([F39] AS float) AS [return_air_temp],
    CAST([F40] AS float) AS [return_air_humidity],
    CAST([F41] AS float) AS [mixed_air_temp],
    CAST([F42] AS float) AS [mixed_air_humidity],
    CAST([F1] AS float) AS [chilled_water_supply_temp],
    CAST([F2] AS float) AS [chilled_water_supply_pressure],
    CAST(NULL AS float) AS [heat_steam_temp],
    CAST(NULL AS float) AS [heat_steam_pressure],
    CAST(NULL AS float) AS [humidify_steam_temp],
    CAST(NULL AS float) AS [humidify_steam_pressure],
    CAST([F43] AS float) AS [fan_frequency]
FROM [dbo].[GYZky];';

    EXEC sys.sp_executesql N'CREATE VIEW [dbo].[KTStartData_K04] AS
SELECT
    [Ct] AS [CT],
    CAST([F44] AS float) AS [workshop_temp_avg],
    CAST([F45] AS float) AS [workshop_humidity_avg],
    CAST([F46] AS float) AS [ac_temp_setpoint],
    CAST([F47] AS float) AS [ac_humidity_setpoint],
    CAST([F61] AS float) AS [fresh_air_temp],
    CAST([F62] AS float) AS [fresh_air_humidity],
    CAST([F50] AS float) AS [supply_air_temp],
    CAST([F51] AS float) AS [supply_air_humidity],
    CAST([F52] AS float) AS [return_air_temp],
    CAST([F53] AS float) AS [return_air_humidity],
    CAST([F54] AS float) AS [mixed_air_temp],
    CAST([F55] AS float) AS [mixed_air_humidity],
    CAST([F1] AS float) AS [chilled_water_supply_temp],
    CAST([F2] AS float) AS [chilled_water_supply_pressure],
    CAST(NULL AS float) AS [heat_steam_temp],
    CAST(NULL AS float) AS [heat_steam_pressure],
    CAST(NULL AS float) AS [humidify_steam_temp],
    CAST(NULL AS float) AS [humidify_steam_pressure],
    CAST([F56] AS float) AS [fan_frequency]
FROM [dbo].[GYZky];';

    EXEC sys.sp_executesql N'CREATE VIEW [dbo].[KTStartData_K05] AS
SELECT
    [Ct] AS [CT],
    CAST([F57] AS float) AS [workshop_temp_avg],
    CAST([F58] AS float) AS [workshop_humidity_avg],
    CAST([F59] AS float) AS [ac_temp_setpoint],
    CAST([F60] AS float) AS [ac_humidity_setpoint],
    CAST([F61] AS float) AS [fresh_air_temp],
    CAST([F62] AS float) AS [fresh_air_humidity],
    CAST([F63] AS float) AS [supply_air_temp],
    CAST([F64] AS float) AS [supply_air_humidity],
    CAST([F65] AS float) AS [return_air_temp],
    CAST([F66] AS float) AS [return_air_humidity],
    CAST([F67] AS float) AS [mixed_air_temp],
    CAST([F68] AS float) AS [mixed_air_humidity],
    CAST([F1] AS float) AS [chilled_water_supply_temp],
    CAST([F2] AS float) AS [chilled_water_supply_pressure],
    CAST(NULL AS float) AS [heat_steam_temp],
    CAST(NULL AS float) AS [heat_steam_pressure],
    CAST(NULL AS float) AS [humidify_steam_temp],
    CAST(NULL AS float) AS [humidify_steam_pressure],
    CAST([F69] AS float) AS [fan_frequency]
FROM [dbo].[GYZky];';

    EXEC sys.sp_executesql N'CREATE VIEW [dbo].[KTStartData_K06] AS
SELECT
    [Ct] AS [CT],
    CAST([F70] AS float) AS [workshop_temp_avg],
    CAST([F71] AS float) AS [workshop_humidity_avg],
    CAST([F72] AS float) AS [ac_temp_setpoint],
    CAST([F73] AS float) AS [ac_humidity_setpoint],
    CAST([F74] AS float) AS [fresh_air_temp],
    CAST([F75] AS float) AS [fresh_air_humidity],
    CAST([F76] AS float) AS [supply_air_temp],
    CAST([F77] AS float) AS [supply_air_humidity],
    CAST([F78] AS float) AS [return_air_temp],
    CAST([F79] AS float) AS [return_air_humidity],
    CAST([F80] AS float) AS [mixed_air_temp],
    CAST([F81] AS float) AS [mixed_air_humidity],
    CAST([F1] AS float) AS [chilled_water_supply_temp],
    CAST([F2] AS float) AS [chilled_water_supply_pressure],
    CAST(NULL AS float) AS [heat_steam_temp],
    CAST(NULL AS float) AS [heat_steam_pressure],
    CAST(NULL AS float) AS [humidify_steam_temp],
    CAST(NULL AS float) AS [humidify_steam_pressure],
    CAST([F82] AS float) AS [fan_frequency]
FROM [dbo].[GYZky];';

    EXEC sys.sp_executesql N'CREATE VIEW [dbo].[KTStartData_K07] AS
SELECT
    [Ct] AS [CT],
    CAST([F83] AS float) AS [workshop_temp_avg],
    CAST([F84] AS float) AS [workshop_humidity_avg],
    CAST([F85] AS float) AS [ac_temp_setpoint],
    CAST([F86] AS float) AS [ac_humidity_setpoint],
    CAST([F74] AS float) AS [fresh_air_temp],
    CAST([F75] AS float) AS [fresh_air_humidity],
    CAST([F89] AS float) AS [supply_air_temp],
    CAST([F90] AS float) AS [supply_air_humidity],
    CAST([F91] AS float) AS [return_air_temp],
    CAST([F92] AS float) AS [return_air_humidity],
    CAST([F93] AS float) AS [mixed_air_temp],
    CAST([F94] AS float) AS [mixed_air_humidity],
    CAST([F1] AS float) AS [chilled_water_supply_temp],
    CAST([F2] AS float) AS [chilled_water_supply_pressure],
    CAST(NULL AS float) AS [heat_steam_temp],
    CAST(NULL AS float) AS [heat_steam_pressure],
    CAST(NULL AS float) AS [humidify_steam_temp],
    CAST(NULL AS float) AS [humidify_steam_pressure],
    CAST([F95] AS float) AS [fan_frequency]
FROM [dbo].[GYZky];';

    EXEC sys.sp_executesql N'CREATE VIEW [dbo].[KTStartData_K08] AS
SELECT
    [Ct] AS [CT],
    CAST([F96] AS float) AS [workshop_temp_avg],
    CAST([F97] AS float) AS [workshop_humidity_avg],
    CAST([F98] AS float) AS [ac_temp_setpoint],
    CAST([F99] AS float) AS [ac_humidity_setpoint],
    CAST([F113] AS float) AS [fresh_air_temp],
    CAST([F114] AS float) AS [fresh_air_humidity],
    CAST([F102] AS float) AS [supply_air_temp],
    CAST([F103] AS float) AS [supply_air_humidity],
    CAST([F104] AS float) AS [return_air_temp],
    CAST([F105] AS float) AS [return_air_humidity],
    CAST([F106] AS float) AS [mixed_air_temp],
    CAST([F107] AS float) AS [mixed_air_humidity],
    CAST([F1] AS float) AS [chilled_water_supply_temp],
    CAST([F2] AS float) AS [chilled_water_supply_pressure],
    CAST(NULL AS float) AS [heat_steam_temp],
    CAST(NULL AS float) AS [heat_steam_pressure],
    CAST(NULL AS float) AS [humidify_steam_temp],
    CAST(NULL AS float) AS [humidify_steam_pressure],
    CAST([F108] AS float) AS [fan_frequency]
FROM [dbo].[GYZky];';

    EXEC sys.sp_executesql N'CREATE VIEW [dbo].[KTStartData_K09] AS
SELECT
    [Ct] AS [CT],
    CAST([F109] AS float) AS [workshop_temp_avg],
    CAST([F110] AS float) AS [workshop_humidity_avg],
    CAST([F111] AS float) AS [ac_temp_setpoint],
    CAST([F112] AS float) AS [ac_humidity_setpoint],
    CAST([F113] AS float) AS [fresh_air_temp],
    CAST([F114] AS float) AS [fresh_air_humidity],
    CAST([F115] AS float) AS [supply_air_temp],
    CAST([F116] AS float) AS [supply_air_humidity],
    CAST([F117] AS float) AS [return_air_temp],
    CAST([F118] AS float) AS [return_air_humidity],
    CAST([F119] AS float) AS [mixed_air_temp],
    CAST([F120] AS float) AS [mixed_air_humidity],
    CAST([F1] AS float) AS [chilled_water_supply_temp],
    CAST([F2] AS float) AS [chilled_water_supply_pressure],
    CAST(NULL AS float) AS [heat_steam_temp],
    CAST(NULL AS float) AS [heat_steam_pressure],
    CAST(NULL AS float) AS [humidify_steam_temp],
    CAST(NULL AS float) AS [humidify_steam_pressure],
    CAST([F121] AS float) AS [fan_frequency]
FROM [dbo].[GYZky];';

    EXEC sys.sp_executesql N'CREATE VIEW [dbo].[KTStartData_K10] AS
SELECT
    [Ct] AS [CT],
    CAST([F122] AS float) AS [workshop_temp_avg],
    CAST([F123] AS float) AS [workshop_humidity_avg],
    CAST([F124] AS float) AS [ac_temp_setpoint],
    CAST([F125] AS float) AS [ac_humidity_setpoint],
    CAST([F139] AS float) AS [fresh_air_temp],
    CAST([F140] AS float) AS [fresh_air_humidity],
    CAST([F128] AS float) AS [supply_air_temp],
    CAST([F129] AS float) AS [supply_air_humidity],
    CAST([F130] AS float) AS [return_air_temp],
    CAST([F131] AS float) AS [return_air_humidity],
    CAST([F132] AS float) AS [mixed_air_temp],
    CAST([F133] AS float) AS [mixed_air_humidity],
    CAST([F1] AS float) AS [chilled_water_supply_temp],
    CAST([F2] AS float) AS [chilled_water_supply_pressure],
    CAST(NULL AS float) AS [heat_steam_temp],
    CAST(NULL AS float) AS [heat_steam_pressure],
    CAST(NULL AS float) AS [humidify_steam_temp],
    CAST(NULL AS float) AS [humidify_steam_pressure],
    CAST([F134] AS float) AS [fan_frequency]
FROM [dbo].[GYZky];';

    EXEC sys.sp_executesql N'CREATE VIEW [dbo].[KTStartData_K11] AS
SELECT
    [Ct] AS [CT],
    CAST([F135] AS float) AS [workshop_temp_avg],
    CAST([F136] AS float) AS [workshop_humidity_avg],
    CAST([F137] AS float) AS [ac_temp_setpoint],
    CAST([F138] AS float) AS [ac_humidity_setpoint],
    CAST([F139] AS float) AS [fresh_air_temp],
    CAST([F140] AS float) AS [fresh_air_humidity],
    CAST([F141] AS float) AS [supply_air_temp],
    CAST([F142] AS float) AS [supply_air_humidity],
    CAST([F143] AS float) AS [return_air_temp],
    CAST([F144] AS float) AS [return_air_humidity],
    CAST([F145] AS float) AS [mixed_air_temp],
    CAST([F146] AS float) AS [mixed_air_humidity],
    CAST([F1] AS float) AS [chilled_water_supply_temp],
    CAST([F2] AS float) AS [chilled_water_supply_pressure],
    CAST(NULL AS float) AS [heat_steam_temp],
    CAST(NULL AS float) AS [heat_steam_pressure],
    CAST(NULL AS float) AS [humidify_steam_temp],
    CAST(NULL AS float) AS [humidify_steam_pressure],
    CAST([F147] AS float) AS [fan_frequency]
FROM [dbo].[GYZky];';

    EXEC sys.sp_executesql N'CREATE VIEW [dbo].[KTStartData_K12] AS
SELECT
    [Ct] AS [CT],
    CAST([F148] AS float) AS [workshop_temp_avg],
    CAST([F149] AS float) AS [workshop_humidity_avg],
    CAST([F150] AS float) AS [ac_temp_setpoint],
    CAST([F151] AS float) AS [ac_humidity_setpoint],
    CAST([F165] AS float) AS [fresh_air_temp],
    CAST([F166] AS float) AS [fresh_air_humidity],
    CAST([F154] AS float) AS [supply_air_temp],
    CAST([F155] AS float) AS [supply_air_humidity],
    CAST([F156] AS float) AS [return_air_temp],
    CAST([F157] AS float) AS [return_air_humidity],
    CAST([F158] AS float) AS [mixed_air_temp],
    CAST([F159] AS float) AS [mixed_air_humidity],
    CAST([F1] AS float) AS [chilled_water_supply_temp],
    CAST([F2] AS float) AS [chilled_water_supply_pressure],
    CAST(NULL AS float) AS [heat_steam_temp],
    CAST(NULL AS float) AS [heat_steam_pressure],
    CAST(NULL AS float) AS [humidify_steam_temp],
    CAST(NULL AS float) AS [humidify_steam_pressure],
    CAST([F160] AS float) AS [fan_frequency]
FROM [dbo].[GYZky];';

    EXEC sys.sp_executesql N'CREATE VIEW [dbo].[KTStartData_K13] AS
SELECT
    [Ct] AS [CT],
    CAST([F161] AS float) AS [workshop_temp_avg],
    CAST([F162] AS float) AS [workshop_humidity_avg],
    CAST([F163] AS float) AS [ac_temp_setpoint],
    CAST([F164] AS float) AS [ac_humidity_setpoint],
    CAST([F165] AS float) AS [fresh_air_temp],
    CAST([F166] AS float) AS [fresh_air_humidity],
    CAST([F167] AS float) AS [supply_air_temp],
    CAST([F168] AS float) AS [supply_air_humidity],
    CAST([F169] AS float) AS [return_air_temp],
    CAST([F170] AS float) AS [return_air_humidity],
    CAST([F171] AS float) AS [mixed_air_temp],
    CAST([F172] AS float) AS [mixed_air_humidity],
    CAST([F1] AS float) AS [chilled_water_supply_temp],
    CAST([F2] AS float) AS [chilled_water_supply_pressure],
    CAST(NULL AS float) AS [heat_steam_temp],
    CAST(NULL AS float) AS [heat_steam_pressure],
    CAST(NULL AS float) AS [humidify_steam_temp],
    CAST(NULL AS float) AS [humidify_steam_pressure],
    CAST([F173] AS float) AS [fan_frequency]
FROM [dbo].[GYZky];';

    EXEC sys.sp_executesql N'CREATE VIEW [dbo].[KTStartData_K14] AS
SELECT
    [Ct] AS [CT],
    CAST([F174] AS float) AS [workshop_temp_avg],
    CAST([F175] AS float) AS [workshop_humidity_avg],
    CAST([F176] AS float) AS [ac_temp_setpoint],
    CAST([F177] AS float) AS [ac_humidity_setpoint],
    CAST([F191] AS float) AS [fresh_air_temp],
    CAST([F192] AS float) AS [fresh_air_humidity],
    CAST([F180] AS float) AS [supply_air_temp],
    CAST([F181] AS float) AS [supply_air_humidity],
    CAST([F182] AS float) AS [return_air_temp],
    CAST([F183] AS float) AS [return_air_humidity],
    CAST([F184] AS float) AS [mixed_air_temp],
    CAST([F185] AS float) AS [mixed_air_humidity],
    CAST([F1] AS float) AS [chilled_water_supply_temp],
    CAST([F2] AS float) AS [chilled_water_supply_pressure],
    CAST(NULL AS float) AS [heat_steam_temp],
    CAST(NULL AS float) AS [heat_steam_pressure],
    CAST(NULL AS float) AS [humidify_steam_temp],
    CAST(NULL AS float) AS [humidify_steam_pressure],
    CAST([F186] AS float) AS [fan_frequency]
FROM [dbo].[GYZky];';

    EXEC sys.sp_executesql N'CREATE VIEW [dbo].[KTStartData_K15] AS
SELECT
    [Ct] AS [CT],
    CAST([F187] AS float) AS [workshop_temp_avg],
    CAST([F188] AS float) AS [workshop_humidity_avg],
    CAST([F189] AS float) AS [ac_temp_setpoint],
    CAST([F190] AS float) AS [ac_humidity_setpoint],
    CAST([F191] AS float) AS [fresh_air_temp],
    CAST([F192] AS float) AS [fresh_air_humidity],
    CAST([F193] AS float) AS [supply_air_temp],
    CAST([F194] AS float) AS [supply_air_humidity],
    CAST([F195] AS float) AS [return_air_temp],
    CAST([F196] AS float) AS [return_air_humidity],
    CAST([F197] AS float) AS [mixed_air_temp],
    CAST([F198] AS float) AS [mixed_air_humidity],
    CAST([F1] AS float) AS [chilled_water_supply_temp],
    CAST([F2] AS float) AS [chilled_water_supply_pressure],
    CAST(NULL AS float) AS [heat_steam_temp],
    CAST(NULL AS float) AS [heat_steam_pressure],
    CAST(NULL AS float) AS [humidify_steam_temp],
    CAST(NULL AS float) AS [humidify_steam_pressure],
    CAST([F199] AS float) AS [fan_frequency]
FROM [dbo].[GYZky];';

    EXEC sys.sp_executesql N'CREATE VIEW [dbo].[KTStartData_K16] AS
SELECT
    [Ct] AS [CT],
    CAST([F200] AS float) AS [workshop_temp_avg],
    CAST([F201] AS float) AS [workshop_humidity_avg],
    CAST([F202] AS float) AS [ac_temp_setpoint],
    CAST([F203] AS float) AS [ac_humidity_setpoint],
    CAST([F191] AS float) AS [fresh_air_temp],
    CAST([F192] AS float) AS [fresh_air_humidity],
    CAST([F206] AS float) AS [supply_air_temp],
    CAST([F207] AS float) AS [supply_air_humidity],
    CAST([F208] AS float) AS [return_air_temp],
    CAST([F209] AS float) AS [return_air_humidity],
    CAST([F210] AS float) AS [mixed_air_temp],
    CAST([F211] AS float) AS [mixed_air_humidity],
    CAST([F1] AS float) AS [chilled_water_supply_temp],
    CAST([F2] AS float) AS [chilled_water_supply_pressure],
    CAST(NULL AS float) AS [heat_steam_temp],
    CAST(NULL AS float) AS [heat_steam_pressure],
    CAST(NULL AS float) AS [humidify_steam_temp],
    CAST(NULL AS float) AS [humidify_steam_pressure],
    CAST([F212] AS float) AS [fan_frequency]
FROM [dbo].[GYZky];';

    EXEC sys.sp_executesql N'CREATE VIEW [dbo].[KTStartData_K17] AS
SELECT
    [Ct] AS [CT],
    CAST([F213] AS float) AS [workshop_temp_avg],
    CAST([F214] AS float) AS [workshop_humidity_avg],
    CAST([F215] AS float) AS [ac_temp_setpoint],
    CAST([F216] AS float) AS [ac_humidity_setpoint],
    CAST([F191] AS float) AS [fresh_air_temp],
    CAST([F192] AS float) AS [fresh_air_humidity],
    CAST([F219] AS float) AS [supply_air_temp],
    CAST([F220] AS float) AS [supply_air_humidity],
    CAST([F221] AS float) AS [return_air_temp],
    CAST([F222] AS float) AS [return_air_humidity],
    CAST([F223] AS float) AS [mixed_air_temp],
    CAST([F224] AS float) AS [mixed_air_humidity],
    CAST([F1] AS float) AS [chilled_water_supply_temp],
    CAST([F2] AS float) AS [chilled_water_supply_pressure],
    CAST(NULL AS float) AS [heat_steam_temp],
    CAST(NULL AS float) AS [heat_steam_pressure],
    CAST(NULL AS float) AS [humidify_steam_temp],
    CAST(NULL AS float) AS [humidify_steam_pressure],
    CAST([F225] AS float) AS [fan_frequency]
FROM [dbo].[GYZky];';

    EXEC sys.sp_executesql N'CREATE VIEW [dbo].[KTStartData_K20] AS
SELECT
    [Ct] AS [CT],
    CAST([F226] AS float) AS [workshop_temp_avg],
    CAST([F227] AS float) AS [workshop_humidity_avg],
    CAST([F228] AS float) AS [ac_temp_setpoint],
    CAST([F229] AS float) AS [ac_humidity_setpoint],
    CAST([F230] AS float) AS [fresh_air_temp],
    CAST([F231] AS float) AS [fresh_air_humidity],
    CAST([F232] AS float) AS [supply_air_temp],
    CAST([F233] AS float) AS [supply_air_humidity],
    CAST([F234] AS float) AS [return_air_temp],
    CAST([F235] AS float) AS [return_air_humidity],
    CAST([F236] AS float) AS [mixed_air_temp],
    CAST([F237] AS float) AS [mixed_air_humidity],
    CAST([F1] AS float) AS [chilled_water_supply_temp],
    CAST([F2] AS float) AS [chilled_water_supply_pressure],
    CAST(NULL AS float) AS [heat_steam_temp],
    CAST(NULL AS float) AS [heat_steam_pressure],
    CAST(NULL AS float) AS [humidify_steam_temp],
    CAST(NULL AS float) AS [humidify_steam_pressure],
    CAST([F238] AS float) AS [fan_frequency]
FROM [dbo].[GYZky];';

    EXEC sys.sp_executesql N'CREATE VIEW [dbo].[KTStartData_K21] AS
SELECT
    [Ct] AS [CT],
    CAST([F239] AS float) AS [workshop_temp_avg],
    CAST([F240] AS float) AS [workshop_humidity_avg],
    CAST([F241] AS float) AS [ac_temp_setpoint],
    CAST([F242] AS float) AS [ac_humidity_setpoint],
    CAST([F230] AS float) AS [fresh_air_temp],
    CAST([F231] AS float) AS [fresh_air_humidity],
    CAST([F245] AS float) AS [supply_air_temp],
    CAST([F246] AS float) AS [supply_air_humidity],
    CAST([F247] AS float) AS [return_air_temp],
    CAST([F248] AS float) AS [return_air_humidity],
    CAST(NULL AS float) AS [mixed_air_temp],
    CAST(NULL AS float) AS [mixed_air_humidity],
    CAST([F1] AS float) AS [chilled_water_supply_temp],
    CAST([F2] AS float) AS [chilled_water_supply_pressure],
    CAST(NULL AS float) AS [heat_steam_temp],
    CAST(NULL AS float) AS [heat_steam_pressure],
    CAST(NULL AS float) AS [humidify_steam_temp],
    CAST(NULL AS float) AS [humidify_steam_pressure],
    CAST([F249] AS float) AS [fan_frequency]
FROM [dbo].[GYZky];';

    EXEC sys.sp_executesql N'CREATE VIEW [dbo].[KTStartData_K22] AS
SELECT
    [Ct] AS [CT],
    CAST([F250] AS float) AS [workshop_temp_avg],
    CAST([F251] AS float) AS [workshop_humidity_avg],
    CAST([F252] AS float) AS [ac_temp_setpoint],
    CAST([F253] AS float) AS [ac_humidity_setpoint],
    CAST([F254] AS float) AS [fresh_air_temp],
    CAST([F255] AS float) AS [fresh_air_humidity],
    CAST([F256] AS float) AS [supply_air_temp],
    CAST([F257] AS float) AS [supply_air_humidity],
    CAST([F258] AS float) AS [return_air_temp],
    CAST([F259] AS float) AS [return_air_humidity],
    CAST(NULL AS float) AS [mixed_air_temp],
    CAST(NULL AS float) AS [mixed_air_humidity],
    CAST([F1] AS float) AS [chilled_water_supply_temp],
    CAST([F2] AS float) AS [chilled_water_supply_pressure],
    CAST(NULL AS float) AS [heat_steam_temp],
    CAST(NULL AS float) AS [heat_steam_pressure],
    CAST(NULL AS float) AS [humidify_steam_temp],
    CAST(NULL AS float) AS [humidify_steam_pressure],
    CAST([F260] AS float) AS [fan_frequency]
FROM [dbo].[GYZky];';

    EXEC sys.sp_executesql N'CREATE VIEW [dbo].[KTStartData_K25] AS
SELECT
    [Ct] AS [CT],
    CAST([F261] AS float) AS [workshop_temp_avg],
    CAST([F262] AS float) AS [workshop_humidity_avg],
    CAST([F263] AS float) AS [ac_temp_setpoint],
    CAST([F264] AS float) AS [ac_humidity_setpoint],
    CAST([F265] AS float) AS [fresh_air_temp],
    CAST([F266] AS float) AS [fresh_air_humidity],
    CAST([F267] AS float) AS [supply_air_temp],
    CAST([F268] AS float) AS [supply_air_humidity],
    CAST([F269] AS float) AS [return_air_temp],
    CAST([F270] AS float) AS [return_air_humidity],
    CAST([F271] AS float) AS [mixed_air_temp],
    CAST([F272] AS float) AS [mixed_air_humidity],
    CAST([F1] AS float) AS [chilled_water_supply_temp],
    CAST([F2] AS float) AS [chilled_water_supply_pressure],
    CAST(NULL AS float) AS [heat_steam_temp],
    CAST(NULL AS float) AS [heat_steam_pressure],
    CAST(NULL AS float) AS [humidify_steam_temp],
    CAST(NULL AS float) AS [humidify_steam_pressure],
    CAST([F273] AS float) AS [fan_frequency]
FROM [dbo].[GYZky];';

    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    IF XACT_STATE() <> 0 ROLLBACK TRANSACTION;
    THROW;
END CATCH;

SELECT v.name AS source_object, COUNT(c.column_id) AS column_count
FROM @views AS v
JOIN sys.columns AS c ON c.object_id = OBJECT_ID(N'dbo.' + QUOTENAME(v.name))
GROUP BY v.name ORDER BY v.name;

SELECT TOP (10) [CT], [workshop_temp_avg], [workshop_humidity_avg],
    [ac_temp_setpoint], [ac_humidity_setpoint], [fresh_air_temp], [fan_frequency]
FROM [dbo].[KTStartData_K01] ORDER BY [CT] DESC;
