/**
 * @fileoverview info-card —— 信息卡片：一块摆 1..N 个读数，一格纵向四段
 * 「徽章·标签 ｜ 读数 + 单位 ｜ 涨跌块 ｜ 脚注」，排布、格外壳、标签、数值、单位、图标
 * 六组档位正交可配。参考仓 kpi-card / kpi-group / icon-kpi-group 三个模块收敛成本模块
 * 的五套预设，见 docs/MODULE_INFO_CARD_DESIGN.md。
 *
 * ⚠ 类型 id 是 `info-card` 而不是 `card`：守「零模块类型字面量」的那道闸按已注册的
 * type 逐个 grep 源码，`card` 这种常见词会红在一堆与模块毫不相干的属性上。
 */
import type { BindingRowLabel } from '@dt/contracts'

import { defineModule } from '../../registry'
import type { CardItem } from './cells'
import {
  CARD_ITEMS_KEY,
  CARD_SLOT_KEY,
  cardFieldKey,
  readCardItems,
} from './cells'
import {
  CARD_ALIGNS,
  CARD_CELL_SHELLS,
  CARD_COLUMNS,
  CARD_COMPARE_MODES,
  CARD_HOVERS,
  CARD_ICON_MODES,
  CARD_ICON_POSITIONS,
  CARD_ICON_SHAPES,
  CARD_LABEL_PLACES,
  CARD_LABEL_TONES,
  CARD_LAYOUTS,
  CARD_STATUS_DOTS,
  CARD_UNIT_PLACES,
  CARD_UNIT_TONES,
  CARD_VALUE_FILLS,
  CARD_VALUE_FONTS,
  CARD_VALUE_KINDS,
} from './options'
import { INFO_CARD_PRESETS } from './presets'
import { valueRulesField } from './rules'

/**
 * 绑点面板上每一格叫什么：名字给人看，联动值给人核对。
 * ⚠ 没配名称的格在墙上不画标签行，但在绑点面板上仍得有个称呼——十几格全靠数行号
 * 认对象，是这套面板最容易接错的地方。
 * @param items 归一化后的格列表
 */
function rowLabels(
  items: readonly CardItem[],
): Record<string, BindingRowLabel> {
  const labels: Record<string, BindingRowLabel> = {}
  items.forEach((item, index) => {
    labels[cardFieldKey(index, 'value')] = {
      title: item.label === '' ? `第 ${index + 1} 格` : item.label,
      id: item.emitValue,
    }
  })
  return labels
}

export default defineModule({
  type: 'info-card',
  description:
    '信息卡片用于呈现一组固定 KPI，支持图标、数值、单位、状态规则和环比信息；需要自由组合内容时可选可组合卡片，需要量程图形时可选仪表卡片。数据通过 cardValues 数组绑定，第 i 行对应 items 第 i 项，value 为主值，aux 为对比基准。删除或调整 items 顺序会改变后续绑定索引，操作后必须复核绑定。',
  displayName: '信息卡片',
  category: '数据',
  icon: 'layout-grid',
  keywords: [
    'infocard',
    'kapian',
    'zhibiao',
    'kpi',
    '信息卡片',
    '卡片',
    '指标',
    '读数',
    '气象',
  ],
  defaultSize: { width: 420, height: 220, minWidth: 120, minHeight: 64 },
  configPresets: INFO_CARD_PRESETS,
  contentKeys: ['title', CARD_ITEMS_KEY, 'emptyText', 'rules'],
  configSchema: [
    {
      key: 'title',
      label: '标题',
      type: 'string',
      group: '内容',
      default: '',
      span: 'full',
      placeholder: '留空则隐藏标题栏',
    },
    {
      key: CARD_ITEMS_KEY,
      label: '格',
      type: 'array',
      group: '内容',
      help: '每项对应一个绑定行。删除中间项会使后续绑定索引前移，操作后请复核绑定。',
      itemLabelKey: 'label',
      minItems: 1,
      // ⚠ 出厂给一项：空列表时模块是一块什么都没有的白板，而属性面板上
      //   「新增一行」不在最显眼的位置，看着像模块坏了
      default: [{ label: '点位 1', unit: '', precision: 1 }],
      span: 'full',
      itemSchema: [
        {
          key: 'label',
          label: '名称',
          type: 'string',
          default: '',
          placeholder: '留空则隐藏标签',
          // ⚠ 留空不是「回落一个默认名」：整行不渲染，档位类名也跟着不挂，
          //   挂了会多出一列空网格 + 一个列间距，读数偏移几像素
          help: '数据格名称；留空则隐藏标签，绑定面板仍按序号标识。',
        },
        {
          key: 'unit',
          label: '单位',
          type: 'string',
          default: '',
          placeholder: '例如：℃ / kWh / m³/h',
          // ⚠ 不去首尾空格：「° C」这类带空格是用户显式的排版意图
          help: '保留首尾空格，可用于控制单位与读数的间距。',
        },
        {
          key: 'precision',
          label: '小数位',
          type: 'range',
          default: 1,
          min: 0,
          max: 6,
          step: 1,
        },
        {
          key: 'valueKind',
          label: '值类型',
          type: 'enum',
          default: 'number',
          help: '仅数值类型参与取值规则计算；布尔值与文本不匹配阈值，也不显示规则颜色。',
          options: [...CARD_VALUE_KINDS],
        },
        {
          key: 'trueText',
          label: '真值文案',
          type: 'string',
          default: '运行',
          when: { key: 'valueKind', in: ['boolean'] },
        },
        {
          key: 'falseText',
          label: '假值文案',
          type: 'string',
          default: '停止',
          when: { key: 'valueKind', in: ['boolean'] },
        },
        {
          key: 'emoji',
          label: 'emoji 图标',
          type: 'string',
          default: '',
          placeholder: '例如：🌡️ 💧 🌧️',
        },
        {
          key: 'icon',
          label: '素材图标',
          type: 'image',
          default: '',
          help: '优先使用素材库图标；留空时使用 emoji，两者均为空时隐藏图标。',
        },
        {
          key: 'color',
          label: '固定颜色',
          type: 'color',
          default: '',
          help: '设置数据格基础色并停用渐变；规则命中色优先。建议使用 var(--…) 主题变量。',
        },
        {
          key: 'emitValue',
          label: '联动值',
          type: 'string',
          default: '',
          help: '点击数据格时发送的联动值；留空则不发送格级事件。',
        },
      ],
    },
    {
      key: 'emptyText',
      label: '缺值占位',
      type: 'string',
      group: '内容',
      default: '—',
      span: 'half',
      help: '数据缺失时显示在读数位置的占位符；缺失值不会转换为 0。',
    },
    {
      key: 'layout',
      label: '排布',
      type: 'enum',
      group: '排布',
      default: 'auto',
      span: 'half',
      help: '自动模式下，单个数据格突出显示，多个数据格使用网格排列。',
      options: [...CARD_LAYOUTS],
    },
    {
      key: 'columns',
      label: '列数',
      type: 'enum',
      group: '排布',
      default: 'auto',
      span: 'half',
      help: '自动模式按最小列宽自适应排列，行数随数据格数量调整。',
      options: [...CARD_COLUMNS],
    },
    {
      key: 'gapX',
      label: '列间距 (px)',
      type: 'range',
      group: '排布',
      default: 10,
      min: 0,
      max: 40,
      step: 1,
      span: 'half',
    },
    {
      key: 'gapY',
      label: '行间距 (px)',
      type: 'range',
      group: '排布',
      default: 10,
      min: 0,
      max: 40,
      step: 1,
      span: 'half',
    },
    {
      key: 'padX',
      label: '模块水平内边距 (px)',
      type: 'range',
      group: '排布',
      default: 10,
      min: 0,
      max: 40,
      step: 1,
      span: 'half',
    },
    {
      key: 'padY',
      label: '模块垂直内边距 (px)',
      type: 'range',
      group: '排布',
      default: 6,
      min: 0,
      max: 40,
      step: 1,
      span: 'half',
    },
    {
      key: 'cellShell',
      label: '格外壳',
      type: 'enum',
      group: '外壳',
      default: 'plain',
      span: 'half',
      options: [...CARD_CELL_SHELLS],
    },
    {
      key: 'cellPadX',
      label: '格左右内边距 (px)',
      type: 'range',
      group: '外壳',
      default: 12,
      min: 0,
      max: 40,
      step: 1,
      span: 'half',
    },
    {
      key: 'cellPadY',
      label: '格上下内边距 (px)',
      type: 'range',
      group: '外壳',
      default: 8,
      min: 0,
      max: 40,
      step: 1,
      span: 'half',
    },
    {
      key: 'hover',
      label: '悬停反馈',
      type: 'enum',
      group: '外壳',
      default: 'none',
      span: 'half',
      help: '触摸设备不支持悬停，建议同时配置适用于触摸操作的反馈方式。',
      options: [...CARD_HOVERS],
    },
    {
      key: 'align',
      label: '格内对齐',
      type: 'enum',
      group: '标签',
      default: 'center',
      span: 'half',
      options: [...CARD_ALIGNS],
    },
    {
      key: 'labelPlace',
      label: '标签位置',
      type: 'enum',
      group: '标签',
      default: 'above',
      span: 'half',
      help: '设置标签相对读数的位置；名称留空时不显示标签或占位。',
      options: [...CARD_LABEL_PLACES],
    },
    {
      key: 'labelSize',
      label: '标签字号 (px)',
      type: 'range',
      group: '标签',
      default: 12,
      min: 8,
      max: 48,
      step: 1,
      span: 'half',
    },
    {
      key: 'labelTone',
      label: '标签文字色',
      type: 'enum',
      group: '标签',
      default: 'secondary',
      span: 'half',
      options: [...CARD_LABEL_TONES],
    },
    {
      key: 'labelOpacity',
      label: '标签透明度',
      type: 'range',
      group: '标签',
      default: 1,
      min: 0.2,
      max: 1,
      step: 0.05,
      span: 'half',
    },
    {
      key: 'valueSize',
      label: '读数字号 (px)',
      type: 'range',
      group: '数值',
      default: 0,
      min: 0,
      max: 200,
      step: 1,
      span: 'half',
      help: '0 表示根据数据格宽度自适应；正数表示固定字号，便于多个数据格保持一致。',
    },
    {
      key: 'valueColor',
      label: '读数颜色',
      type: 'color',
      group: '数值',
      // 命中规则的那一格改用规则自己的颜色，这里是没命中时的颜色
      default: 'var(--accent-primary)',
      span: 'half',
      help: '设置未命中取值规则时的颜色；规则命中后优先使用规则颜色。',
    },
    {
      key: 'valueFill',
      label: '读数填充',
      type: 'enum',
      group: '数值',
      default: 'solid',
      span: 'half',
      help: '仅当启用渐变、数据格无固定颜色且未命中规则、读数使用数字字体时生效；其他情况使用纯色。',
      options: [...CARD_VALUE_FILLS],
    },
    {
      key: 'valueGradient',
      label: '渐变色标',
      type: 'array',
      group: '数值',
      default: [],
      maxItems: 6,
      itemLabelKey: 'color',
      span: 'full',
      when: { key: 'valueFill', in: ['gradient'] },
      help: '至少配置 2 个色标才显示渐变，仅配置 1 个时使用纯色。',
      itemSchema: [
        {
          key: 'color',
          label: '色标',
          type: 'color',
          default: 'var(--accent-secondary)',
        },
      ],
    },
    {
      key: 'gradientAngle',
      label: '渐变角度',
      type: 'range',
      group: '数值',
      default: 0,
      min: 0,
      max: 360,
      step: 5,
      span: 'half',
      when: { key: 'valueFill', in: ['gradient'] },
      help: '0 表示自下而上。',
    },
    {
      key: 'valueGlow',
      label: '读数辉光 (px)',
      type: 'range',
      group: '数值',
      default: 0,
      min: 0,
      max: 24,
      step: 1,
      span: 'half',
      help: '渐变文字不显示辉光，避免阴影影响文字清晰度。',
    },
    {
      key: 'valueFont',
      label: '读数字体',
      type: 'enum',
      group: '数值',
      default: 'digit',
      span: 'half',
      help: '数字字体采用等宽样式，可避免读数变化时宽度跳动。',
      options: [...CARD_VALUE_FONTS],
    },
    {
      key: 'textPlainFallback',
      label: '文本值不走渐变',
      type: 'boolean',
      group: '数值',
      default: true,
      span: 'half',
      help: '启用后，文本值与缺值占位使用正文字体和纯色；停用后沿用数值样式。',
    },
    {
      key: 'unit',
      label: '单位',
      type: 'object',
      group: '单位',
      span: 'full',
      default: { place: 'baseline', size: 12, tone: 'secondary', opacity: 1 },
      fields: [
        {
          key: 'place',
          label: '位置',
          type: 'enum',
          default: 'baseline',
          help: '两种位置均与读数保持同一基线，仅间距不同。',
          options: [...CARD_UNIT_PLACES],
        },
        {
          key: 'size',
          label: '字号 (px)',
          type: 'range',
          default: 12,
          min: 8,
          max: 32,
          step: 1,
        },
        {
          key: 'tone',
          label: '文字色',
          type: 'enum',
          default: 'secondary',
          help: '选择「跟随数值色」时，单位同步使用规则命中后的状态颜色。',
          options: [...CARD_UNIT_TONES],
        },
        {
          key: 'opacity',
          label: '透明度',
          type: 'range',
          default: 1,
          min: 0.2,
          max: 1,
          step: 0.05,
        },
      ],
    },
    {
      key: 'thousands',
      label: '千分位分隔',
      type: 'boolean',
      group: '格式',
      default: false,
      span: 'half',
    },
    {
      key: 'fixedDecimals',
      label: '固定小数位',
      type: 'boolean',
      group: '格式',
      default: false,
      span: 'half',
      help: '启用后按「小数位」补零对齐（如 42.00 / 3.50），保持读数位数稳定。',
    },
    {
      key: 'icon',
      label: '图标',
      type: 'object',
      group: '图标',
      span: 'full',
      help: '角标固定在数据格右上角，图标容器随文字排列；两者均使用此处配置的素材图标或 emoji。',
      default: {
        mode: 'none',
        position: 'left',
        size: 20,
        shape: 'circle',
        bgFrom: '',
        bgTo: '',
        bgAngle: 135,
        borderColor: '',
        glow: 8,
        gap: 10,
        fontSize: 18,
        opacity: 1,
      },
      fields: [
        {
          key: 'mode',
          label: '样式',
          type: 'enum',
          default: 'none',
          options: [...CARD_ICON_MODES],
        },
        {
          key: 'position',
          label: '方位',
          type: 'enum',
          default: 'left',
          when: { key: 'mode', in: ['badge'] },
          help: '仅影响图标容器；右上角标位置固定，不受此设置影响。',
          options: [...CARD_ICON_POSITIONS],
        },
        {
          key: 'size',
          label: '直径 (px)',
          type: 'range',
          // ⚠ 下限与参考仓 icon-kpi-group 的 `iconSize` 同为 16，也与取值层的夹取同值：
          //   这里放宽到 12 的话，面板能拖到 12 而渲染仍按 16 画——「配了不生效」
          default: 20,
          min: 16,
          max: 96,
          step: 1,
        },
        {
          key: 'shape',
          label: '形状',
          type: 'enum',
          default: 'circle',
          when: { key: 'mode', in: ['badge'] },
          options: [...CARD_ICON_SHAPES],
        },
        {
          key: 'bgFrom',
          label: '底色起',
          type: 'color',
          default: '',
          when: { key: 'mode', in: ['badge'] },
          placeholder: '留空时跟随强调色',
        },
        {
          key: 'bgTo',
          label: '底色止',
          type: 'color',
          default: '',
          when: { key: 'mode', in: ['badge'] },
          placeholder: '留空时跟随强调色',
        },
        {
          key: 'bgAngle',
          label: '底渐变角',
          type: 'range',
          default: 135,
          min: 0,
          max: 360,
          step: 5,
          when: { key: 'mode', in: ['badge'] },
        },
        {
          key: 'borderColor',
          label: '描边色',
          type: 'color',
          default: '',
          when: { key: 'mode', in: ['badge'] },
          placeholder: '留空时跟随强调色',
        },
        {
          key: 'glow',
          label: '外发光 (px)',
          type: 'range',
          default: 8,
          min: 0,
          max: 24,
          step: 1,
          when: { key: 'mode', in: ['badge'] },
        },
        {
          key: 'gap',
          label: '与文字间距 (px)',
          type: 'range',
          default: 10,
          min: 0,
          max: 40,
          step: 1,
          when: { key: 'mode', in: ['badge'] },
        },
        {
          key: 'fontSize',
          label: 'emoji 字号 (px)',
          type: 'range',
          default: 18,
          min: 8,
          max: 48,
          step: 1,
          help: '只影响 emoji；素材图标按容器直径等比内缩。',
        },
        {
          key: 'opacity',
          label: '透明度',
          type: 'range',
          default: 1,
          min: 0.2,
          max: 1,
          step: 0.05,
        },
      ],
    },
    {
      key: 'compare',
      label: '涨跌对比',
      type: 'object',
      group: '对比',
      span: 'full',
      help: '需绑定「对比值」子槽；当前值或对比值缺失时不显示。',
      default: { show: false, mode: 'percent', label: '', invertTrend: false },
      fields: [
        { key: 'show', label: '显示涨跌块', type: 'boolean', default: false },
        {
          key: 'mode',
          label: '对比方式',
          type: 'enum',
          default: 'percent',
          when: { key: 'show', in: [true] },
          help: '对比基数为 0 时，百分比模式改为显示绝对差值。',
          options: [...CARD_COMPARE_MODES],
        },
        {
          key: 'label',
          label: '标注',
          type: 'string',
          default: '',
          when: { key: 'show', in: [true] },
          placeholder: '例如：较上期 / 目标',
        },
        {
          key: 'invertTrend',
          label: '下降为好',
          type: 'boolean',
          default: false,
          when: { key: 'show', in: [true] },
          help: '启用后将数值下降标记为正向变化，适用于能耗或成本指标。',
        },
      ],
    },
    { ...valueRulesField('rules', '取值规则'), group: '告警' },
    {
      key: 'statusDot',
      label: '状态点',
      type: 'enum',
      group: '告警',
      default: 'none',
      span: 'half',
      help: '仅在命中取值规则时显示状态点；未配置有效判据时不显示。',
      options: [...CARD_STATUS_DOTS],
    },
  ],
  bindings: [
    {
      key: CARD_SLOT_KEY,
      label: '卡片读数',
      // ⚠ 只影响 static 常量那一档的输入控件，不过滤可选点位
      dataType: 'number',
      isArray: true,
      // 格钉在配置里的项上：格数由配置决定，绑一部分格是常态，空出来的格
      // 不许让其后整体移位（DASHBOARD_DESIGN §4.2）
      isEntityPinned: true,
      // ⚠ 一个子槽都不给 isRequired：配了 10 格先接 3 个是常态，
      //   给了会让整块被判 unbound 并盖上状态浮层，逐格四档白画
      arrayFields: [
        { key: 'value', label: '主读数', dataType: 'number' },
        { key: 'aux', label: '对比值（上期 / 目标）', dataType: 'number' },
      ],
    },
  ],
  // 十格里坏掉一格不该让另外九格一起被浮层盖住，四档由模块自己逐格交代
  ownsStatusDisplay: true,
  // 点某一格上抛这一格的联动值（配了联动值的格才抛）
  emitsInteractions: true,
  // 整块可点由宿主接管；格内点击在模板里 `.stop`，否则同一次点击会被兜底再抛一次
  hostClickable: true,
  bindingRowLabels: (config) =>
    rowLabels(readCardItems(config[CARD_ITEMS_KEY])),
  // ⚠ 格不是用户在绑点面板上随手加的：行号就是格的文档序。不声明行数的话，
  //   面板会摆出「新增一行」，加出来的那一行永远喂不到任何东西。
  //   ⚠ 一格都没有时也要给 0，别把键漏掉
  bindingRowCounts: (config) => ({
    [CARD_SLOT_KEY]: readCardItems(config[CARD_ITEMS_KEY]).length,
  }),
  preview: {
    config: {
      [CARD_ITEMS_KEY]: [
        { label: '温度', emoji: '🌡️', unit: '℃', precision: 1 },
        { label: '湿度', emoji: '💧', unit: '%', precision: 0 },
        { label: '气压', emoji: '🌐', unit: 'hPa', precision: 0 },
      ],
    },
    values: {
      [CARD_SLOT_KEY]: [{ value: 23.4 }, { value: 61 }, { value: 1013 }],
    },
  },
  component: () => import('./Component.vue'),
})
