/**
 * @fileoverview info-card —— 信息卡片：一块摆 1..N 个读数，一格纵向四段
 * 「徽章·标签 ｜ 读数 + 单位 ｜ 涨跌块 ｜ 脚注」，排布、格外壳、标签、数值、单位、图标
 * 六组档位正交可配。参考仓 kpi-card / kpi-group / icon-kpi-group 三个模块收敛成本模块
 * 的五套预设，见 docs/MODULE_INFO_CARD_DESIGN.md。
 *
 * ⚠ 类型 id 是 `info-card` 而不是 `card`：守「零模块类型字面量」的那道闸按已注册的
 * type 逐个 grep 源码，`card` 这种常见词会红在一堆与模块毫不相干的属性上。
 */
import type { BindingRowLabel } from '@dt/contracts'

import { defineModule } from '../../registry'
import type { CardItem } from './cells'
import {
  CARD_ITEMS_KEY,
  CARD_SLOT_KEY,
  cardFieldKey,
  readCardItems,
} from './cells'
import {
  CARD_ALIGNS,
  CARD_CELL_SHELLS,
  CARD_COLUMNS,
  CARD_COMPARE_MODES,
  CARD_HOVERS,
  CARD_ICON_MODES,
  CARD_ICON_POSITIONS,
  CARD_ICON_SHAPES,
  CARD_LABEL_PLACES,
  CARD_LABEL_TONES,
  CARD_LAYOUTS,
  CARD_STATUS_DOTS,
  CARD_UNIT_PLACES,
  CARD_UNIT_TONES,
  CARD_VALUE_FILLS,
  CARD_VALUE_FONTS,
  CARD_VALUE_KINDS,
} from './options'
import { INFO_CARD_PRESETS } from './presets'
import { valueRulesField } from './rules'

/**
 * 绑点面板上每一格叫什么：名字给人看，联动值给人核对。
 * ⚠ 没配名称的格在墙上不画标签行，但在绑点面板上仍得有个称呼——十几格全靠数行号
 * 认对象，是这套面板最容易接错的地方。
 * @param items 归一化后的格列表
 */
function rowLabels(
  items: readonly CardItem[],
): Record<string, BindingRowLabel> {
  const labels: Record<string, BindingRowLabel> = {}
  items.forEach((item, index) => {
    labels[cardFieldKey(index, 'value')] = {
      title: item.label === '' ? `第 ${index + 1} 格` : item.label,
      id: item.emitValue,
    }
  })
  return labels
}

export default defineModule({
  type: 'info-card',
  description:
    '信息卡片：一块摆 1..N 个格，一格纵向四段「徽章·标签 ｜ 读数 + 单位 ｜ 涨跌块 ｜ 脚注」，排布、格外壳、标签、数值、单位、图标六组档位正交可配，读数可走渐变文字与素材图标 / emoji。要一屏好看的 KPI 网格、带图标或带「较上期」对比时用它；要自己拼段序、或要在格里嵌进度条用 data-card，要量程 / 进度 / 液位那种图形用 gauge-card，要竖着一列多字段的行用 info-list。一个数组绑定槽 `cardValues`，行钉在 `items` 配置项上：第 i 行喂第 i 格，子槽 `value` 是主读数、`aux` 是涨跌块要的对比值（上期 / 目标），都收数值；单位、小数位、emoji 与固定颜色是逐格的配置项，不从点位来。⚠ 涨跌块要 `value` 与 `aux` 两个子槽都有值才画，缺一整块不出。⚠ 删掉 `items` 中间一格，它之后每一格的绑定都会改喂前一格。',
  displayName: '信息卡片',
  category: '数据',
  icon: 'layout-grid',
  keywords: [
    'infocard',
    'kapian',
    'zhibiao',
    'kpi',
    '信息卡片',
    '卡片',
    '指标',
    '读数',
    '气象',
  ],
  defaultSize: { width: 420, height: 220, minWidth: 120, minHeight: 64 },
  configPresets: INFO_CARD_PRESETS,
  contentKeys: ['title', CARD_ITEMS_KEY, 'emptyText', 'rules'],
  configSchema: [
    {
      key: 'title',
      label: '标题',
      type: 'string',
      group: '内容',
      default: '',
      span: 'full',
      placeholder: '留空则不画标题栏',
    },
    {
      key: CARD_ITEMS_KEY,
      label: '格',
      type: 'array',
      group: '内容',
      help: '每一项在绑点面板上是一行。⚠ 删掉中间一项，它之后每一格的绑定都会改喂前一格——删完请核对绑点面板。',
      itemLabelKey: 'label',
      minItems: 1,
      // ⚠ 出厂给一项：空列表时模块是一块什么都没有的白板，而属性面板上
      //   「新增一行」不在最显眼的位置，看着像模块坏了
      default: [{ label: '点位 1', unit: '', precision: 1 }],
      span: 'full',
      itemSchema: [
        {
          key: 'label',
          label: '名称',
          type: 'string',
          default: '',
          placeholder: '留空则这一格不画标签行',
          // ⚠ 留空不是「回落一个默认名」：整行不渲染，档位类名也跟着不挂，
          //   挂了会多出一列空网格 + 一个列间距，读数偏移几像素
          help: '这一格的名称；留空则不画标签行。绑点面板上仍按「第 N 格」称呼它。',
        },
        {
          key: 'unit',
          label: '单位',
          type: 'string',
          default: '',
          placeholder: '如 ℃ / kWh / m³/h',
          // ⚠ 不去首尾空格：「° C」这类带空格是用户显式的排版意图
          help: '首尾空格照原样保留，「° C」这种写法是有意的排版。',
        },
        {
          key: 'precision',
          label: '小数位',
          type: 'range',
          default: 1,
          min: 0,
          max: 6,
          step: 1,
        },
        {
          key: 'valueKind',
          label: '值类型',
          type: 'enum',
          default: 'number',
          help: '⚠ 只有数值档会去评估取值规则：开关量与文本命中不了阈值，也就没有告警色。',
          options: [...CARD_VALUE_KINDS],
        },
        {
          key: 'trueText',
          label: '真值文案',
          type: 'string',
          default: '运行',
          when: { key: 'valueKind', in: ['boolean'] },
        },
        {
          key: 'falseText',
          label: '假值文案',
          type: 'string',
          default: '停止',
          when: { key: 'valueKind', in: ['boolean'] },
        },
        {
          key: 'emoji',
          label: 'emoji 图标',
          type: 'string',
          default: '',
          placeholder: '如 🌡️ 💧 🌧️',
        },
        {
          key: 'icon',
          label: '素材图标',
          type: 'image',
          default: '',
          help: '素材库里的图标；留空则用 emoji，两者都留空时这一格不画图标。',
        },
        {
          key: 'color',
          label: '固定颜色',
          type: 'color',
          default: '',
          help: '填了就固定这一格的读数颜色并压过渐变与规则命中色。只填 var(--…) 引用，填死色值换肤时不跟着走。',
        },
        {
          key: 'emitValue',
          label: '联动值',
          type: 'string',
          default: '',
          help: '点这一格时上抛的值，留空则这一格点了不上抛。',
        },
      ],
    },
    {
      key: 'emptyText',
      label: '缺值占位',
      type: 'string',
      group: '内容',
      default: '—',
      span: 'half',
      help: '取不到值时画在读数位的那个符号。⚠ 缺值绝不伪造 0。',
    },
    {
      key: 'layout',
      label: '排布',
      type: 'enum',
      group: '排布',
      default: 'auto',
      span: 'half',
      help: '自动 = 只有一格时大字铺满，多格时按网格。',
      options: [...CARD_LAYOUTS],
    },
    {
      key: 'columns',
      label: '列数',
      type: 'enum',
      group: '排布',
      default: 'auto',
      span: 'half',
      help: '自动 = 按最小列宽自适应铺满；行数一律随格数自适应，没有单独的行数档。',
      options: [...CARD_COLUMNS],
    },
    {
      key: 'gapX',
      label: '列间距 (px)',
      type: 'range',
      group: '排布',
      default: 10,
      min: 0,
      max: 40,
      step: 1,
      span: 'half',
    },
    {
      key: 'gapY',
      label: '行间距 (px)',
      type: 'range',
      group: '排布',
      default: 10,
      min: 0,
      max: 40,
      step: 1,
      span: 'half',
    },
    {
      key: 'padX',
      label: '整块左右内边距 (px)',
      type: 'range',
      group: '排布',
      default: 10,
      min: 0,
      max: 40,
      step: 1,
      span: 'half',
    },
    {
      key: 'padY',
      label: '整块上下内边距 (px)',
      type: 'range',
      group: '排布',
      default: 6,
      min: 0,
      max: 40,
      step: 1,
      span: 'half',
    },
    {
      key: 'cellShell',
      label: '格外壳',
      type: 'enum',
      group: '外壳',
      default: 'plain',
      span: 'half',
      options: [...CARD_CELL_SHELLS],
    },
    {
      key: 'cellPadX',
      label: '格左右内边距 (px)',
      type: 'range',
      group: '外壳',
      default: 12,
      min: 0,
      max: 40,
      step: 1,
      span: 'half',
    },
    {
      key: 'cellPadY',
      label: '格上下内边距 (px)',
      type: 'range',
      group: '外壳',
      default: 8,
      min: 0,
      max: 40,
      step: 1,
      span: 'half',
    },
    {
      key: 'hover',
      label: '悬停反馈',
      type: 'enum',
      group: '外壳',
      default: 'none',
      span: 'half',
      help: '⚠ 触摸屏没有悬停：只靠这一档的大屏，手指按上去是没有反馈的。',
      options: [...CARD_HOVERS],
    },
    {
      key: 'align',
      label: '格内对齐',
      type: 'enum',
      group: '标签',
      default: 'center',
      span: 'half',
      options: [...CARD_ALIGNS],
    },
    {
      key: 'labelPlace',
      label: '标签位置',
      type: 'enum',
      group: '标签',
      default: 'above',
      span: 'half',
      help: '⚠ 它只管摆在哪儿，不管显不显示：这一格没有名称时整行不渲染，也不占位。要藏某一格的标签，把那一项的「名称」留空。',
      options: [...CARD_LABEL_PLACES],
    },
    {
      key: 'labelSize',
      label: '标签字号 (px)',
      type: 'range',
      group: '标签',
      default: 12,
      min: 8,
      max: 48,
      step: 1,
      span: 'half',
    },
    {
      key: 'labelTone',
      label: '标签文字色',
      type: 'enum',
      group: '标签',
      default: 'secondary',
      span: 'half',
      options: [...CARD_LABEL_TONES],
    },
    {
      key: 'labelOpacity',
      label: '标签透明度',
      type: 'range',
      group: '标签',
      default: 1,
      min: 0.2,
      max: 1,
      step: 0.05,
      span: 'half',
    },
    {
      key: 'valueSize',
      label: '读数字号 (px)',
      type: 'range',
      group: '数值',
      default: 0,
      min: 0,
      max: 200,
      step: 1,
      span: 'half',
      help: '0 = 跟着格宽自适应。填正数即钉死一个字号，多格并排时字号才对得齐。',
    },
    {
      key: 'valueColor',
      label: '读数颜色',
      type: 'color',
      group: '数值',
      // 命中规则的那一格改用规则自己的颜色，这里是没命中时的颜色
      default: 'var(--accent-primary)',
      span: 'half',
      help: '命中取值规则的那一格改用规则的颜色，这里配的是没有命中时的颜色。',
    },
    {
      key: 'valueFill',
      label: '读数填充',
      type: 'enum',
      group: '数值',
      default: 'solid',
      span: 'half',
      help: '⚠ 渐变文字有三个前提：模块开了渐变、这一格没有固定颜色也没命中规则、这个值有资格用数字字体。缺一即静默回落纯色。',
      options: [...CARD_VALUE_FILLS],
    },
    {
      key: 'valueGradient',
      label: '渐变色标',
      type: 'array',
      group: '数值',
      default: [],
      maxItems: 6,
      itemLabelKey: 'color',
      span: 'full',
      when: { key: 'valueFill', in: ['gradient'] },
      help: '≥2 个色标才画渐变，只填一个整组回落纯色。',
      itemSchema: [
        {
          key: 'color',
          label: '色标',
          type: 'color',
          default: 'var(--accent-secondary)',
        },
      ],
    },
    {
      key: 'gradientAngle',
      label: '渐变角度',
      type: 'range',
      group: '数值',
      default: 0,
      min: 0,
      max: 360,
      step: 5,
      span: 'half',
      when: { key: 'valueFill', in: ['gradient'] },
      help: '0 = 自下而上。',
    },
    {
      key: 'valueGlow',
      label: '读数辉光 (px)',
      type: 'range',
      group: '数值',
      default: 0,
      min: 0,
      max: 24,
      step: 1,
      span: 'half',
      help: '⚠ 渐变文字档下辉光一律不画：阴影会糊在字面上。',
    },
    {
      key: 'valueFont',
      label: '读数字体',
      type: 'enum',
      group: '数值',
      default: 'digit',
      span: 'half',
      help: '数字字体是等宽的，读数逐帧跳动时列宽不抖。',
      options: [...CARD_VALUE_FONTS],
    },
    {
      key: 'textPlainFallback',
      label: '文本值不走渐变',
      type: 'boolean',
      group: '数值',
      default: true,
      span: 'half',
      help: '开着时文本值与缺值回落正文字体 + 纯色；关掉则一视同仁。',
    },
    {
      key: 'unit',
      label: '单位',
      type: 'object',
      group: '单位',
      span: 'full',
      default: { place: 'baseline', size: 12, tone: 'secondary', opacity: 1 },
      fields: [
        {
          key: 'place',
          label: '位置',
          type: 'enum',
          default: 'baseline',
          help: '两档都与读数同基线，差的只是那一道小间隙。',
          options: [...CARD_UNIT_PLACES],
        },
        {
          key: 'size',
          label: '字号 (px)',
          type: 'range',
          default: 12,
          min: 8,
          max: 32,
          step: 1,
        },
        {
          key: 'tone',
          label: '文字色',
          type: 'enum',
          default: 'secondary',
          help: '「跟随数值色」会一并跟着命中规则后的告警色走。',
          options: [...CARD_UNIT_TONES],
        },
        {
          key: 'opacity',
          label: '透明度',
          type: 'range',
          default: 1,
          min: 0.2,
          max: 1,
          step: 0.05,
        },
      ],
    },
    {
      key: 'thousands',
      label: '千分位分隔',
      type: 'boolean',
      group: '格式',
      default: false,
      span: 'half',
    },
    {
      key: 'fixedDecimals',
      label: '固定小数位',
      type: 'boolean',
      group: '格式',
      default: false,
      span: 'half',
      help: '开着时按「小数位」补零对齐（42.00 / 3.50），读数跳动时位数不变。',
    },
    {
      key: 'icon',
      label: '图标',
      type: 'object',
      group: '图标',
      span: 'full',
      help: '角标钉在格的右上角，图标容器跟着文字走；两者都取这一项配的素材图标或 emoji。',
      default: {
        mode: 'none',
        position: 'left',
        size: 20,
        shape: 'circle',
        bgFrom: '',
        bgTo: '',
        bgAngle: 135,
        borderColor: '',
        glow: 8,
        gap: 10,
        fontSize: 18,
        opacity: 1,
      },
      fields: [
        {
          key: 'mode',
          label: '画法',
          type: 'enum',
          default: 'none',
          options: [...CARD_ICON_MODES],
        },
        {
          key: 'position',
          label: '方位',
          type: 'enum',
          default: 'left',
          help: '⚠ 只对图标容器生效：右上角标钉死在角上，不看这一项。',
          options: [...CARD_ICON_POSITIONS],
        },
        {
          key: 'size',
          label: '直径 (px)',
          type: 'range',
          // ⚠ 下限与参考仓 icon-kpi-group 的 `iconSize` 同为 16，也与取值层的夹取同值：
          //   这里放宽到 12 的话，面板能拖到 12 而渲染仍按 16 画——「配了不生效」
          default: 20,
          min: 16,
          max: 96,
          step: 1,
        },
        {
          key: 'shape',
          label: '形状',
          type: 'enum',
          default: 'circle',
          options: [...CARD_ICON_SHAPES],
        },
        {
          key: 'bgFrom',
          label: '底色起',
          type: 'color',
          default: '',
          placeholder: '留空 = 跟随强调色',
        },
        {
          key: 'bgTo',
          label: '底色止',
          type: 'color',
          default: '',
          placeholder: '留空 = 跟随强调色',
        },
        {
          key: 'bgAngle',
          label: '底渐变角',
          type: 'range',
          default: 135,
          min: 0,
          max: 360,
          step: 5,
        },
        {
          key: 'borderColor',
          label: '描边色',
          type: 'color',
          default: '',
          placeholder: '留空 = 跟随强调色',
        },
        {
          key: 'glow',
          label: '外发光 (px)',
          type: 'range',
          default: 8,
          min: 0,
          max: 24,
          step: 1,
        },
        {
          key: 'gap',
          label: '与文字间距 (px)',
          type: 'range',
          default: 10,
          min: 0,
          max: 40,
          step: 1,
        },
        {
          key: 'fontSize',
          label: 'emoji 字号 (px)',
          type: 'range',
          default: 18,
          min: 8,
          max: 48,
          step: 1,
          help: '只影响 emoji；素材图标按容器直径等比内缩。',
        },
        {
          key: 'opacity',
          label: '透明度',
          type: 'range',
          default: 1,
          min: 0.2,
          max: 1,
          step: 0.05,
        },
      ],
    },
    {
      key: 'compare',
      label: '涨跌对比',
      type: 'object',
      group: '对比',
      span: 'full',
      help: '要接「对比值」子槽才画：当前值与对比值任一缺席时整块不出。',
      default: { show: false, mode: 'percent', label: '', invertTrend: false },
      fields: [
        { key: 'show', label: '显示涨跌块', type: 'boolean', default: false },
        {
          key: 'mode',
          label: '显示什么',
          type: 'enum',
          default: 'percent',
          help: '⚠ 百分比档在对比基数为 0 时回退显绝对差值，不留空。',
          options: [...CARD_COMPARE_MODES],
        },
        {
          key: 'label',
          label: '标注',
          type: 'string',
          default: '',
          placeholder: '如 较上期 / 目标',
        },
        {
          key: 'invertTrend',
          label: '下降为好',
          type: 'boolean',
          default: false,
          help: '开着时数值下降显绿（能耗 / 成本类指标）。',
        },
      ],
    },
    { ...valueRulesField('rules', '取值规则'), group: '告警' },
    {
      key: 'statusDot',
      label: '状态点',
      type: 'enum',
      group: '告警',
      default: 'none',
      span: 'half',
      help: '⚠ 只在命中规则时画点：没有判据就连「正常」都不该说。',
      options: [...CARD_STATUS_DOTS],
    },
  ],
  bindings: [
    {
      key: CARD_SLOT_KEY,
      label: '卡片读数',
      // ⚠ 只影响 static 常量那一档的输入控件，不过滤可选点位
      dataType: 'number',
      isArray: true,
      // 格钉在配置里的项上：格数由配置决定，绑一部分格是常态，空出来的格
      // 不许让其后整体移位（DASHBOARD_DESIGN §4.2）
      isEntityPinned: true,
      // ⚠ 一个子槽都不给 isRequired：配了 10 格先接 3 个是常态，
      //   给了会让整块被判 unbound 并盖上状态浮层，逐格四档白画
      arrayFields: [
        { key: 'value', label: '主读数', dataType: 'number' },
        { key: 'aux', label: '对比值（上期 / 目标）', dataType: 'number' },
      ],
    },
  ],
  // 十格里坏掉一格不该让另外九格一起被浮层盖住，四档由模块自己逐格交代
  ownsStatusDisplay: true,
  // 点某一格上抛这一格的联动值（配了联动值的格才抛）
  emitsInteractions: true,
  // 整块可点由宿主接管；格内点击在模板里 `.stop`，否则同一次点击会被兜底再抛一次
  hostClickable: true,
  bindingRowLabels: (config) =>
    rowLabels(readCardItems(config[CARD_ITEMS_KEY])),
  // ⚠ 格不是用户在绑点面板上随手加的：行号就是格的文档序。不声明行数的话，
  //   面板会摆出「新增一行」，加出来的那一行永远喂不到任何东西。
  //   ⚠ 一格都没有时也要给 0，别把键漏掉
  bindingRowCounts: (config) => ({
    [CARD_SLOT_KEY]: readCardItems(config[CARD_ITEMS_KEY]).length,
  }),
  preview: {
    config: {
      [CARD_ITEMS_KEY]: [
        { label: '温度', emoji: '🌡️', unit: '℃', precision: 1 },
        { label: '湿度', emoji: '💧', unit: '%', precision: 0 },
        { label: '气压', emoji: '🌐', unit: 'hPa', precision: 0 },
      ],
    },
    values: {
      [CARD_SLOT_KEY]: [{ value: 23.4 }, { value: 61 }, { value: 1013 }],
    },
  },
  component: () => import('./Component.vue'),
})
