/**
 * @fileoverview info-card 的五套外观预设：参考仓 kpi-card / kpi-group / icon-kpi-group
 * 三个各写一遍的卡片模块，逐值落成这里的前四套，第五套是它们去掉外壳与图标的密排档
 * （MODULE_INFO_CARD_DESIGN §1.3 与 §7）。
 *
 * ⚠ 每套都把「观感」那 30 个键写全，且簇内子键顺序与该字段 `default` 逐字相同。
 * 应用预设是**浅合并**：少写一个键，上一套留在 configJson 里的那个值就原样残留，
 * 而点亮判定做的是子集比较、照样把按钮点亮——既错了又没有任何提示。
 * ⚠ `title` / `items` / `emptyText` 三个内容键一个都不写：预设换的是观感，
 * 写了它们就会把用户配好的格整片抹掉。
 * ⚠ 取值一律以参考仓源码为准，不以覆盖表的缩写为准：`columns` 的档值是字符串
 * `'2'` 而不是数字 2，写成数字判不中白名单、静默回落「自动」。
 */
import type { ConfigPreset } from '@dt/contracts'

export const INFO_CARD_PRESETS: ConfigPreset[] = [
  {
    id: 'kpi-single',
    label: '单值大字',
    hint: '一块一个读数，居中大字 + 下方标签 + 涨跌对比。',
    config: {
      layout: 'single',
      columns: 'auto',
      gapX: 10,
      gapY: 10,
      // 参考仓 .kpi-body 的 padding: 4px 12px 全在整块上，格自己不再留白，
      // 否则单格档下左右留白翻倍
      padX: 12,
      padY: 4,
      cellShell: 'plain',
      cellPadX: 0,
      cellPadY: 0,
      hover: 'none',
      align: 'center',
      labelPlace: 'below',
      labelSize: 12,
      labelTone: 'secondary',
      labelOpacity: 1,
      valueSize: 0,
      valueColor: 'var(--accent-primary)',
      valueFill: 'solid',
      valueGradient: [],
      gradientAngle: 0,
      valueGlow: 12,
      valueFont: 'digit',
      textPlainFallback: true,
      unit: { place: 'baseline', size: 13, tone: 'secondary', opacity: 1 },
      thousands: false,
      fixedDecimals: false,
      icon: {
        mode: 'corner',
        position: 'left',
        size: 20,
        shape: 'circle',
        bgFrom: '',
        bgTo: '',
        bgAngle: 135,
        borderColor: '',
        glow: 8,
        gap: 10,
        fontSize: 18,
        opacity: 0.85,
      },
      compare: { show: true, mode: 'percent', label: '', invertTrend: false },
      rules: [],
      statusDot: 'none',
    },
  },
  {
    id: 'kpi-grid',
    label: '指标小卡',
    hint: '自适应网格，每格描边渐变小卡 + 左侧发光竖条。',
    config: {
      layout: 'grid',
      columns: 'auto',
      gapX: 10,
      gapY: 10,
      padX: 10,
      padY: 6,
      cellShell: 'accent',
      cellPadX: 12,
      cellPadY: 8,
      // 参考仓 .kpi-cell:hover 是描边转强调色 + translateY(-2px) + 投影，有位移故是上浮档
      hover: 'lift',
      align: 'left',
      labelPlace: 'above',
      labelSize: 12,
      labelTone: 'secondary',
      labelOpacity: 1,
      valueSize: 0,
      valueColor: 'var(--accent-primary)',
      valueFill: 'solid',
      valueGradient: [],
      gradientAngle: 0,
      valueGlow: 10,
      valueFont: 'digit',
      textPlainFallback: true,
      unit: { place: 'baseline', size: 12, tone: 'secondary', opacity: 1 },
      thousands: false,
      fixedDecimals: false,
      icon: {
        mode: 'none',
        position: 'left',
        size: 20,
        shape: 'circle',
        bgFrom: '',
        bgTo: '',
        bgAngle: 135,
        borderColor: '',
        glow: 8,
        gap: 10,
        fontSize: 18,
        opacity: 1,
      },
      compare: { show: false, mode: 'percent', label: '', invertTrend: false },
      rules: [],
      statusDot: 'none',
    },
  },
  {
    id: 'icon-grid',
    label: '图标网格',
    hint: '圆形图标 + 右侧「标签上 / 读数下」，气象与环境量的排法。',
    config: {
      layout: 'grid',
      // ⚠ 字符串档值：参考仓 columns 的缺省就是 '2'，写成数字 2 判不中白名单
      columns: '2',
      gapX: 0,
      gapY: 0,
      padX: 0,
      padY: 0,
      cellShell: 'plain',
      cellPadX: 10,
      cellPadY: 5,
      // 参考仓的悬停开关缺省是关的，观感也是「底色提亮 + 上浮」两件事一起，这里不替它打开
      hover: 'none',
      align: 'left',
      labelPlace: 'above',
      labelSize: 13,
      labelTone: 'title',
      labelOpacity: 0.6,
      valueSize: 26,
      valueColor: 'var(--accent-primary)',
      valueFill: 'solid',
      valueGradient: [],
      gradientAngle: 0,
      valueGlow: 0,
      valueFont: 'digit',
      textPlainFallback: true,
      // ⚠ 参考仓单位是标题色压到 50% 透明度，而单位层级四档里没有标题档，
      //   取最接近的正文档
      unit: { place: 'baseline', size: 12, tone: 'primary', opacity: 0.5 },
      thousands: false,
      fixedDecimals: false,
      icon: {
        mode: 'badge',
        position: 'left',
        size: 40,
        shape: 'circle',
        // ⚠ 参考仓这三处填的是 --card-icon-bg-start / -end / -border，本仓没有这三个
        //   token；留空即由取值层用 accent 调 color-mix，填进去等于把底色与描边写没
        bgFrom: '',
        bgTo: '',
        bgAngle: 135,
        borderColor: '',
        glow: 8,
        gap: 10,
        fontSize: 18,
        opacity: 1,
      },
      compare: { show: false, mode: 'percent', label: '', invertTrend: false },
      rules: [],
      statusDot: 'none',
    },
  },
  {
    id: 'icon-column',
    label: '图标竖排',
    hint: '图标在上、标签与读数居中，窄块用。',
    config: {
      layout: 'grid',
      columns: '2',
      gapX: 0,
      gapY: 0,
      padX: 0,
      padY: 0,
      cellShell: 'plain',
      cellPadX: 10,
      cellPadY: 5,
      hover: 'none',
      // 参考仓 .ikg--iconTop 的格是 flex-direction: column + text-align: center，
      // 所以竖排档必须连对齐一起换，只换图标方位会得到「图标在上、文字仍左对齐」
      align: 'center',
      labelPlace: 'above',
      labelSize: 13,
      labelTone: 'title',
      labelOpacity: 0.6,
      valueSize: 26,
      valueColor: 'var(--accent-primary)',
      valueFill: 'solid',
      valueGradient: [],
      gradientAngle: 0,
      valueGlow: 0,
      valueFont: 'digit',
      textPlainFallback: true,
      unit: { place: 'baseline', size: 12, tone: 'primary', opacity: 0.5 },
      thousands: false,
      fixedDecimals: false,
      icon: {
        mode: 'badge',
        position: 'top',
        size: 40,
        shape: 'circle',
        bgFrom: '',
        bgTo: '',
        bgAngle: 135,
        borderColor: '',
        glow: 8,
        gap: 10,
        fontSize: 18,
        opacity: 1,
      },
      compare: { show: false, mode: 'percent', label: '', invertTrend: false },
      rules: [],
      statusDot: 'none',
    },
  },
  {
    id: 'plain-grid',
    label: '裸排网格',
    hint: '无边框无底，纯标签与读数，密排大屏用。',
    config: {
      layout: 'grid',
      columns: 'auto',
      gapX: 8,
      gapY: 8,
      padX: 8,
      padY: 6,
      cellShell: 'plain',
      cellPadX: 8,
      cellPadY: 6,
      hover: 'none',
      align: 'left',
      labelPlace: 'above',
      labelSize: 12,
      labelTone: 'secondary',
      labelOpacity: 1,
      valueSize: 0,
      valueColor: 'var(--accent-primary)',
      valueFill: 'solid',
      valueGradient: [],
      gradientAngle: 0,
      valueGlow: 0,
      valueFont: 'digit',
      textPlainFallback: true,
      unit: { place: 'baseline', size: 12, tone: 'secondary', opacity: 1 },
      thousands: false,
      fixedDecimals: false,
      icon: {
        mode: 'none',
        position: 'left',
        size: 20,
        shape: 'circle',
        bgFrom: '',
        bgTo: '',
        bgAngle: 135,
        borderColor: '',
        glow: 8,
        gap: 10,
        fontSize: 18,
        opacity: 1,
      },
      compare: { show: false, mode: 'percent', label: '', invertTrend: false },
      rules: [],
      statusDot: 'none',
    },
  },
]
