/**
 * @fileoverview image-block —— 装饰图片块：从素材库挑一张，或填一个图片 URL / 一段
 * CSS background 值，再给一组画面调节（填充、圆角、旋转、滤镜）。不取任何数。
 */
import { defineModule } from '../../registry'

export default defineModule({
  type: 'image-block',
  description:
    '静态图片模块，支持素材引用、图片地址及 CSS 背景值，并提供填充、定位、变换和滤镜配置。适用于标识、底图和说明图；需要依据实时值切换内容时，应使用状态类模块。模块不含数据绑定，素材引用可在不同部署间保持稳定。平铺仅适用于 CSS 背景值，替代文字仅作用于实际图片元素。',
  displayName: '图片块',
  category: '装饰',
  icon: 'image',
  keywords: ['image', 'picture', 'tupian', '图片', '图', 'logo'],
  chrome: 'bare',
  hostClickable: true,
  contentKeys: ['title', 'src', 'alt', 'emptyText', 'errorText'],
  defaultSize: { width: 240, height: 108, minWidth: 40, minHeight: 24 },
  configSchema: [
    {
      key: 'title',
      label: '标题',
      type: 'string',
      group: '内容',
      default: '',
      span: 'full',
      placeholder: '留空则隐藏标题栏',
    },
    {
      key: 'src',
      label: '图片',
      type: 'image',
      group: '内容',
      default: '',
      span: 'full',
      placeholder: 'https://… 或 linear-gradient(…)',
      help: '支持素材引用（推荐）、图片地址或 CSS background；素材引用可在部署变更后保持稳定。',
    },
    {
      key: 'alt',
      label: '替代文字',
      type: 'string',
      group: '内容',
      default: '',
      span: 'full',
      help: '供读屏软件识别图片内容；纯装饰图应留空。',
    },
    {
      key: 'emptyText',
      label: '未配图文案',
      type: 'string',
      group: '内容',
      default: '未设置图片',
      span: 'half',
      help: '未配置图片时显示；留空则不显示文字。',
    },
    {
      key: 'errorText',
      label: '加载失败文案',
      type: 'string',
      group: '内容',
      default: '图片加载失败',
      span: 'half',
      help: '图片加载失败时显示；留空则不显示文字。',
    },
    {
      key: 'fit',
      label: '填充方式',
      type: 'enum',
      group: '画面',
      default: 'contain',
      span: 'half',
      options: [
        { value: 'contain', label: '完整' },
        { value: 'cover', label: '裁剪填满' },
        { value: 'fill', label: '拉伸' },
      ],
    },
    {
      key: 'position',
      label: '裁剪定位',
      type: 'enum',
      group: '画面',
      default: 'center',
      span: 'half',
      help: '在裁剪或完整显示时确定图片对齐位置；拉伸时不生效。',
      options: [
        { value: 'center', label: '居中' },
        { value: 'top', label: '上' },
        { value: 'bottom', label: '下' },
        { value: 'left', label: '左' },
        { value: 'right', label: '右' },
      ],
    },
    {
      key: 'repeat',
      label: '平铺',
      type: 'enum',
      group: '画面',
      default: 'no-repeat',
      span: 'half',
      // ⚠ 只对「CSS 值」那条路生效：`<img>` 走的是 object-fit，没有平铺这回事
      help: '仅对 CSS background 值生效，可用于重复铺设底纹。',
      options: [
        { value: 'no-repeat', label: '不平铺' },
        { value: 'repeat', label: '双向平铺' },
        { value: 'repeat-x', label: '横向平铺' },
        { value: 'repeat-y', label: '纵向平铺' },
      ],
    },
    {
      key: 'opacity',
      label: '不透明度 (%)',
      type: 'range',
      group: '画面',
      default: 100,
      min: 0,
      max: 100,
      step: 1,
      span: 'half',
      // ⚠ 量纲是 0–100（百分比），与文本块同名字段的 0–1 不是一回事：
      //   两边各自锁死，改任何一边的取值范围都会改存量大屏的渲染
      help: '取值范围为 0–100，100 表示完全不透明。',
    },
    {
      key: 'rounded',
      label: '圆角 (px)',
      type: 'range',
      group: '画面',
      default: 0,
      min: 0,
      max: 400,
      step: 1,
      span: 'half',
    },
    {
      key: 'rotate',
      label: '旋转 (°)',
      type: 'range',
      group: '画面',
      default: 0,
      min: -180,
      max: 180,
      step: 1,
      span: 'half',
    },
    {
      key: 'flipX',
      label: '水平翻转',
      type: 'boolean',
      group: '画面',
      default: false,
      span: 'half',
    },
    {
      key: 'flipY',
      label: '垂直翻转',
      type: 'boolean',
      group: '画面',
      default: false,
      span: 'half',
    },
    {
      key: 'blur',
      label: '模糊 (px)',
      type: 'range',
      group: '滤镜',
      default: 0,
      min: 0,
      max: 50,
      step: 0.5,
      span: 'half',
    },
    {
      key: 'grayscale',
      label: '灰度 (%)',
      type: 'range',
      group: '滤镜',
      default: 0,
      min: 0,
      max: 100,
      step: 1,
      span: 'half',
    },
    {
      key: 'brightness',
      label: '亮度 (%)',
      type: 'range',
      group: '滤镜',
      default: 100,
      min: 0,
      max: 300,
      step: 1,
      span: 'half',
    },
    {
      key: 'contrast',
      label: '对比度 (%)',
      type: 'range',
      group: '滤镜',
      default: 100,
      min: 0,
      max: 300,
      step: 1,
      span: 'half',
    },
    {
      key: 'saturate',
      label: '饱和度 (%)',
      type: 'range',
      group: '滤镜',
      default: 100,
      min: 0,
      max: 300,
      step: 1,
      span: 'half',
    },
    {
      key: 'hueRotate',
      label: '色相旋转 (°)',
      type: 'range',
      group: '滤镜',
      default: 0,
      min: -180,
      max: 180,
      step: 1,
      span: 'half',
      help: '沿色轮旋转整幅图片的色相；0 表示不处理。',
    },
    {
      key: 'invert',
      label: '反相 (%)',
      type: 'range',
      group: '滤镜',
      default: 0,
      min: 0,
      max: 100,
      step: 1,
      span: 'half',
      help: '100 表示完全反色，常用于将深色图标转换为浅色显示。',
    },
    {
      key: 'sepia',
      label: '褪色 (%)',
      type: 'range',
      group: '滤镜',
      default: 0,
      min: 0,
      max: 100,
      step: 1,
      span: 'half',
      help: '100 表示完整应用棕褐色调。',
    },
  ],
  // 装饰图片不取数：按读数换图请用状态类模块，那边才有阈值与枚举映射
  bindings: [],
  preview: {
    config: {
      src: 'linear-gradient(135deg, var(--accent-primary), transparent)',
      fit: 'cover',
    },
  },
  component: () => import('./Component.vue'),
})
