/**
 * @fileoverview nav-tabs —— 页签栏：一排互斥的页签，点一格上抛一次 `select`
 * 联动事件。跳到哪张大屏、显隐哪一组节点都由大屏级联动规则决定，
 * 模块自己不认识任何一种动作（与 action-button 同一条口径）。
 *
 * ⚠ 目标大屏存在规则里而不是这份配置里：节点配置是**逐字透传**给公开载荷的，
 * 把大屏 id 配进页签等于让匿名页面带上内部标识（ADR-0014），而公开态要的是
 * 目标屏的公开令牌——服务端只改写 `chromeJson.interactions` 里的句柄
 * （DASHBOARD_NAV_DESIGN §6）。「当前在哪一格」同样由规则推：宿主拿当前这张屏的
 * 句柄跟路由目标比，比中的那一格就是高亮（`meta.activeValue`）。
 *
 * ⚠ 类型 id 是 `nav-tabs` 而不是 `tabs`：守「运行时与编辑器里零模块类型
 * 字面量」的两道闸按已注册的 type 逐个 grep 源码，而 `tabs` 是 DtSegmented
 * 的一个 variant 取值，叫它会红在一堆与模块毫不相干的地方。
 */
import { defineModule } from '../../registry'
import {
  TABS_ALIGNS,
  TABS_HOVERS,
  TABS_ICONS,
  TABS_INDICATORS,
  TABS_ITEM_ALIGNS,
  TABS_ORIENTATIONS,
  TABS_PRESSES,
  TABS_SHAPES,
  TABS_SIZINGS,
  TABS_TONES,
  TABS_VALIGNS,
  TABS_VARIANTS,
} from './options'

export default defineModule({
  type: 'nav-tabs',
  description:
    '互斥页签控件，选择一项后发送带值的 `select` 联动事件。跨屏导航应配置「按值跳转大屏」，同屏分区应配置「按值互斥切换」；单一入口应使用按钮。模块不含数据绑定，目标大屏仅保存在联动规则中，避免公开配置泄露内部标识。联动值为空的页签仅改变本地选中态，不触发规则。',
  displayName: '页签栏',
  category: '控件',
  icon: 'panel-tabs',
  keywords: [
    'tabs',
    'nav',
    'yeqian',
    '页签',
    '标签',
    '导航',
    '切换',
    '分段',
    '控件',
  ],
  // 自己画完整的轨道与格子：再套一层卡片框就是两层边框，且圆角与切角对不齐
  chrome: 'bare',
  chromeConfigurable: false,
  defaultSize: { width: 420, height: 48, minWidth: 80, minHeight: 28 },
  // ⚠ 不开 hostClickable：每一格自己就是那个可点的东西，整块再兜底一次的话，
  // 格子之外的空白也能点，且那一次点击不带值，会命中「值留空」那条路径
  emitsInteractions: true,
  // 只发「选项点击」：它是带值的那一档，也是进场重放互斥组认的那一档
  interactionEvents: ['select'],
  bindings: [],
  contentKeys: ['items', 'activeIndex'],
  configPresets: [
    {
      id: 'control-track',
      label: '凹槽控件',
      hint: '槽里浮着一块选中块，与平台里的分段切换器同一套观感。',
      config: {
        variant: 'track',
        tone: 'primary',
        shape: 'rounded',
        itemRadius: 6,
        trackRadius: 10,
        trackPadding: 3,
        borderWidth: 1,
        indicator: 'bar',
        divider: false,
        glow: false,
        hover: 'tint',
      },
    },
    {
      id: 'page-tabs',
      label: '页签底线',
      hint: '一条底线加淡染的选中格，与应用里的页签导航同一套观感。',
      config: {
        variant: 'underline',
        tone: 'primary',
        shape: 'rounded',
        itemRadius: 6,
        trackRadius: 0,
        trackPadding: 0,
        borderWidth: 1,
        indicator: 'bar',
        divider: false,
        glow: false,
        hover: 'tint',
      },
    },
    {
      id: 'hud-cut',
      label: '科技切角',
      hint: '斜切角 + 亮边斜面 + 选中辉光，与页头、按钮的科技风一致。',
      config: {
        variant: 'hud',
        tone: 'primary',
        shape: 'cut',
        itemRadius: 10,
        trackRadius: 0,
        trackPadding: 4,
        borderWidth: 1,
        indicator: 'none',
        // ⚠ 切角档的 clip-path 会把格外的分隔线一起削掉，这一套不开它
        divider: false,
        glow: true,
        glowRadius: 14,
        hover: 'glow',
      },
    },
    {
      id: 'solid-pill',
      label: '实心胶囊',
      hint: '选中格整块上主色的胶囊，一眼就看得出当前在哪一格。',
      config: {
        variant: 'solid',
        tone: 'primary',
        shape: 'pill',
        trackRadius: 40,
        trackPadding: 4,
        borderWidth: 0,
        indicator: 'none',
        divider: false,
        glow: false,
        hover: 'tint',
      },
    },
  ],
  configSchema: [
    {
      key: 'items',
      label: '页签',
      type: 'array',
      group: '内容',
      help: '每项对应一个页签；联动值为空时仅更新选中态，不发送事件。',
      itemLabelKey: 'label',
      minItems: 1,
      maxItems: 12,
      // ⚠ 出厂给三格并且各自带上联动值：空轨道看着像模块坏了，而带标签不带值
      //   的出厂配置会让第一次试点击静默无反应
      default: [
        { label: '总览', emitValue: 'overview' },
        { label: '能耗', emitValue: 'energy' },
        { label: '设备', emitValue: 'device' },
      ],
      span: 'full',
      itemSchema: [
        {
          key: 'label',
          label: '文案',
          type: 'string',
          default: '',
          placeholder: '留空显示「页签 N」',
        },
        {
          key: 'emitValue',
          label: '联动值',
          type: 'string',
          default: '',
          help: '随 `select` 事件发送，供按值跳转或互斥规则匹配；留空时不触发联动。',
        },
        {
          key: 'icon',
          label: '图标',
          type: 'enum',
          default: '',
          options: [...TABS_ICONS],
        },
        {
          key: 'disabled',
          label: '禁用',
          type: 'boolean',
          default: false,
          help: '禁用后该项不可聚焦或选择，且不随数据动态变化。',
        },
      ],
    },
    {
      key: 'activeIndex',
      label: '默认选中第几项',
      type: 'number',
      group: '内容',
      default: 1,
      min: 1,
      max: 12,
      step: 1,
      span: 'half',
      help: '页内分区的初始项；跨屏导航的当前项由跳转规则自动确定。',
    },
    {
      key: 'variant',
      label: '风格',
      type: 'enum',
      group: '外观',
      default: 'track',
      span: 'half',
      options: [...TABS_VARIANTS],
    },
    {
      key: 'tone',
      label: '语义色',
      type: 'enum',
      group: '外观',
      default: 'primary',
      span: 'half',
      help: '取主题里的语义色，换肤时整屏页签一起变。',
      options: [...TABS_TONES],
    },
    {
      key: 'accent',
      label: '自定义主色',
      type: 'color',
      group: '外观',
      default: '',
      span: 'half',
      when: { key: 'tone', in: ['custom'] },
      placeholder: '留空时使用主题强调色',
    },
    {
      key: 'textColor',
      label: '未选中文字色',
      type: 'color',
      group: '外观',
      default: '',
      span: 'half',
      placeholder: '留空时使用主题次要文字色',
    },
    {
      key: 'activeTextColor',
      label: '选中文字色',
      type: 'color',
      group: '外观',
      default: '',
      span: 'half',
      placeholder: '留空时根据风格自动设置',
      help: '实心档默认压深色字。自定义主色配浅色时，用这里显式指定字色。',
    },
    {
      key: 'trackColor',
      label: '轨道底色',
      type: 'color',
      group: '外观',
      default: '',
      span: 'half',
      placeholder: '留空时根据风格自动设置',
    },
    {
      key: 'shape',
      label: '每格轮廓',
      type: 'enum',
      group: '外观',
      default: 'rounded',
      span: 'half',
      options: [...TABS_SHAPES],
    },
    {
      key: 'itemRadius',
      label: '每格圆角 / 切角 (px)',
      type: 'range',
      group: '外观',
      default: 6,
      min: 0,
      max: 40,
      step: 1,
      span: 'half',
      when: { key: 'shape', in: ['rounded', 'cut'] },
      help: '圆角档是半径，切角档是斜边的边长。',
    },
    {
      key: 'trackRadius',
      label: '轨道圆角 (px)',
      type: 'range',
      group: '外观',
      default: 10,
      min: 0,
      max: 40,
      step: 1,
      span: 'half',
    },
    {
      key: 'borderWidth',
      label: '描边粗细 (px)',
      type: 'range',
      group: '外观',
      default: 1,
      min: 0,
      max: 4,
      step: 0.5,
      span: 'half',
      help: '同时是轨道与每一格的描边；「页签」风格的那条底线也用它，配 0 就没有线了。',
    },
    {
      key: 'divider',
      label: '分隔线',
      type: 'boolean',
      group: '外观',
      default: false,
      span: 'half',
      help: '格与格之间一条细线。⚠ 「切角」轮廓会把它一起削掉，两者不要同时开。',
    },
    {
      key: 'glow',
      label: '选中辉光',
      type: 'boolean',
      group: '外观',
      default: false,
      span: 'half',
      help: '在选中项外侧显示与主色一致的光晕。',
    },
    {
      key: 'glowRadius',
      label: '辉光半径 (px)',
      type: 'range',
      group: '外观',
      default: 12,
      min: 0,
      max: 40,
      step: 1,
      span: 'half',
      when: { key: 'glow', in: [true] },
    },
    {
      key: 'indicator',
      label: '指示条',
      type: 'enum',
      group: '外观',
      default: 'bar',
      span: 'half',
      help: '设置选中项的高亮条。竖排导航建议使用「首侧竖条」，以保持清晰层级。',
      options: [...TABS_INDICATORS],
    },
    {
      key: 'indicatorSize',
      label: '指示条粗细 (px)',
      type: 'range',
      group: '外观',
      default: 2,
      min: 1,
      max: 12,
      step: 1,
      span: 'half',
      when: { key: 'indicator', in: ['bar', 'edge'] },
    },
    {
      key: 'fontSize',
      label: '字号 (px)',
      type: 'range',
      group: '文字',
      default: 14,
      min: 8,
      max: 64,
      step: 1,
      span: 'half',
    },
    {
      key: 'fontWeight',
      label: '字重',
      type: 'range',
      group: '文字',
      default: 500,
      min: 100,
      max: 900,
      step: 100,
      span: 'half',
    },
    {
      key: 'activeFontWeight',
      label: '选中字重',
      type: 'range',
      group: '文字',
      default: 0,
      min: 0,
      max: 900,
      step: 100,
      span: 'half',
      help: '0 表示沿用普通字重；按内容布局时，不同字重可能引起轨道宽度变化。',
    },
    {
      key: 'letterSpacing',
      label: '字间距 (px)',
      type: 'range',
      group: '文字',
      default: 0,
      min: 0,
      max: 20,
      step: 0.5,
      span: 'half',
    },
    {
      key: 'iconSize',
      label: '图标字号 (px)',
      type: 'range',
      group: '文字',
      default: 0,
      min: 0,
      max: 64,
      step: 1,
      span: 'half',
      help: '0 表示跟随文字字号，约为文字字号的 1.1 倍。',
    },
    {
      key: 'orientation',
      label: '排布方向',
      type: 'enum',
      group: '排布',
      default: 'row',
      span: 'half',
      help: '竖排用来当左侧或右侧的一列导航。',
      options: [...TABS_ORIENTATIONS],
    },
    {
      key: 'itemAlign',
      label: '格内对齐',
      type: 'enum',
      group: '排布',
      default: 'center',
      span: 'half',
      help: '设置图标与文案在选项内的对齐方式。竖排导航通常左对齐，横排导航通常居中。',
      options: [...TABS_ITEM_ALIGNS],
    },
    {
      key: 'sizing',
      label: '尺寸',
      type: 'enum',
      group: '排布',
      default: 'fill',
      span: 'half',
      help: '「充满模块」使用节点矩形尺寸；「按内容」由文字与内边距决定尺寸。',
      options: [...TABS_SIZINGS],
    },
    {
      key: 'stretch',
      label: '每格等分',
      type: 'boolean',
      group: '排布',
      default: true,
      span: 'half',
      help: '启用后各选项均分轨道；关闭后按各自内容宽度收缩。',
    },
    {
      key: 'align',
      label: '水平位置',
      type: 'enum',
      group: '排布',
      default: 'center',
      span: 'half',
      when: { key: 'sizing', in: ['auto'] },
      options: [...TABS_ALIGNS],
    },
    {
      key: 'vAlign',
      label: '垂直位置',
      type: 'enum',
      group: '排布',
      default: 'center',
      span: 'half',
      when: { key: 'sizing', in: ['auto'] },
      options: [...TABS_VALIGNS],
    },
    {
      key: 'gap',
      label: '格间距 (px)',
      type: 'range',
      group: '排布',
      default: 4,
      min: 0,
      max: 40,
      step: 1,
      span: 'half',
    },
    {
      key: 'itemPaddingX',
      label: '格内左右边距 (px)',
      type: 'range',
      group: '排布',
      default: 16,
      min: 0,
      max: 64,
      step: 1,
      span: 'half',
    },
    {
      key: 'itemPaddingY',
      label: '格内上下边距 (px)',
      type: 'range',
      group: '排布',
      default: 8,
      min: 0,
      max: 48,
      step: 1,
      span: 'half',
      help: '「按内容」模式下决定轨道高度；「充满模块」模式下由模块矩形决定高度。',
    },
    {
      key: 'trackPadding',
      label: '轨道内边距 (px)',
      type: 'range',
      group: '排布',
      default: 3,
      min: 0,
      max: 32,
      step: 1,
      span: 'half',
      help: '设置轨道与选项之间的间距；「凹槽」风格依靠该间距呈现层次。',
    },
    {
      key: 'hover',
      label: '悬停反馈',
      type: 'enum',
      group: '动效',
      default: 'tint',
      span: 'half',
      help: '仅作用于未选中项。触摸设备不触发悬停，建议同时配置按下反馈。',
      options: [...TABS_HOVERS],
    },
    {
      key: 'press',
      label: '按下反馈',
      type: 'enum',
      group: '动效',
      default: 'none',
      span: 'half',
      help: '按下时的视觉反馈，适用于鼠标和触摸操作。',
      options: [...TABS_PRESSES],
    },
  ],
  component: () => import('./Component.vue'),
})
