/**
 * @fileoverview action-button —— 按钮控件：点一下上抛一次联动事件，显隐 / 弹窗 / 跨屏跳转
 * 都由大屏级联动规则决定，模块自己不认识任何一种动作。
 *
 * 为什么是一个独立模块而不是「文本块 + 卡片外观」：一个能点的东西必须**长得像能点**，
 * 而那要的是底色、描边、圆角、悬停与按下反馈一整套，不是把一段文字框起来。
 * 键盘可达、禁用语义与读屏角色也只有原生 `<button>` 才是白拿的。
 *
 * ⚠ 类型 id 是 `action-button` 而不是 `button`：守「运行时与编辑器里零模块类型
 * 字面量」的那道闸按已注册的 type 逐个 grep 源码，而模板里到处都是
 * `type="button"` / `role="button"`——叫 `button` 会让那道闸红在十几处无关的
 * 属性上，只能靠给闸门开豁免来消掉，而那正是它守的东西。
 */
import { defineModule } from '../../registry'
import {
  BUTTON_ALIGNS,
  BUTTON_HOVERS,
  BUTTON_ICONS,
  BUTTON_ICON_POSITIONS,
  BUTTON_PRESSES,
  BUTTON_SHAPES,
  BUTTON_SIZINGS,
  BUTTON_TONES,
  BUTTON_VALIGNS,
  BUTTON_VARIANTS,
} from './options'
import { BUTTON_TEXT_DEFAULT } from './look'

/** 需要实际图标才能生效的字段共用这份条件值。 */
const ENABLED_ICONS = BUTTON_ICONS.filter((item) => item.value !== '').map(
  (item) => item.value,
)

export default defineModule({
  type: 'action-button',
  description:
    '原生按钮控件，用于触发大屏联动，不直接执行显隐、弹窗或跳转。需要单一操作入口时选用；仅需文字或图片响应点击时，使用对应的展示模块。模块不含数据绑定；`linkValue` 仅供按值规则分流，留空时发送普通 `click`。未配置联动规则或处于禁用状态时，点击不产生业务动作。',
  displayName: '按钮',
  category: '控件',
  icon: 'square-mouse-pointer',
  keywords: ['button', 'anniu', '按钮', '控件', '交互', '跳转', '入口'],
  // 自己画完整的按钮外观：再套一层卡片框就是两层边框，且圆角与切角对不齐
  chrome: 'bare',
  chromeConfigurable: false,
  defaultSize: { width: 180, height: 52, minWidth: 40, minHeight: 24 },
  // ⚠ 不开 hostClickable：按钮自己就是那个可点的东西，整块再兜底一次的话，
  // 按钮外的空白也能点，且同一次点击会上抛两遍（toggle 类动作当场自我抵消）
  emitsInteractions: true,
  bindings: [],
  contentKeys: ['text', 'subText', 'icon', 'hint', 'linkValue', 'disabled'],
  configPresets: [
    {
      id: 'primary-action',
      label: '主行动',
      hint: '实心主色、圆角与辉光，适用于页面主操作。',
      config: {
        variant: 'solid',
        tone: 'primary',
        shape: 'rounded',
        radius: 8,
        glow: true,
        glowRadius: 14,
        hover: 'brighten',
        press: 'sink',
      },
    },
    {
      id: 'hud-cut',
      label: '科技切角',
      hint: '斜切角 + 亮边斜面 + 悬停扫光，与页头、卡片的科技风一致。',
      config: {
        variant: 'hud',
        tone: 'primary',
        shape: 'cut',
        radius: 12,
        glow: false,
        hover: 'sweep',
        press: 'sink',
      },
    },
    {
      id: 'quiet-outline',
      label: '次要描边',
      hint: '中性描边胶囊，适用于返回或取消等次要操作。',
      config: {
        variant: 'outline',
        tone: 'neutral',
        shape: 'pill',
        borderWidth: 1,
        glow: false,
        hover: 'glow',
        press: 'shrink',
      },
    },
  ],
  configSchema: [
    {
      key: 'text',
      label: '文案',
      type: 'string',
      group: '内容',
      default: BUTTON_TEXT_DEFAULT,
      span: 'full',
      help: '主、副文案均为空时仅显示图标，读屏名称由「悬停提示」提供。',
    },
    {
      key: 'subText',
      label: '副文案',
      type: 'string',
      group: '内容',
      default: '',
      span: 'full',
      placeholder: '留空则隐藏副文案',
      help: '显示在主文案下方，字号按主文案比例计算。',
    },
    {
      key: 'icon',
      label: '图标',
      type: 'enum',
      group: '内容',
      default: '',
      span: 'half',
      options: [...BUTTON_ICONS],
    },
    {
      key: 'iconPosition',
      label: '图标位置',
      type: 'enum',
      group: '内容',
      default: 'left',
      span: 'half',
      when: { key: 'icon', in: ENABLED_ICONS },
      options: [...BUTTON_ICON_POSITIONS],
    },
    {
      key: 'hint',
      label: '悬停提示',
      type: 'string',
      group: '内容',
      default: '',
      span: 'full',
      placeholder: '留空则不提示',
      help: '指针悬停时显示；无可见文案时同时作为读屏名称。',
    },
    {
      key: 'linkValue',
      label: '联动值',
      type: 'string',
      group: '行为',
      default: '',
      span: 'full',
      help: '随点击事件发送，供按值跳转或互斥规则匹配；留空时发送普通 `click`。',
    },
    {
      key: 'disabled',
      label: '禁用',
      type: 'boolean',
      group: '行为',
      default: false,
      span: 'half',
      help: '禁用后不可聚焦或触发。数据驱动的可用性应通过联动显隐控制。',
    },
    {
      key: 'variant',
      label: '风格',
      type: 'enum',
      group: '外观',
      default: 'solid',
      span: 'half',
      options: [...BUTTON_VARIANTS],
    },
    {
      key: 'tone',
      label: '语义色',
      type: 'enum',
      group: '外观',
      default: 'primary',
      span: 'half',
      help: '使用主题语义色，主题切换时同步更新。',
      options: [...BUTTON_TONES],
    },
    {
      key: 'accent',
      label: '自定义主色',
      type: 'color',
      group: '外观',
      default: '',
      span: 'half',
      when: { key: 'tone', in: ['custom'] },
      placeholder: '留空时使用主题强调色',
    },
    {
      key: 'textColor',
      label: '文字色',
      type: 'color',
      group: '外观',
      default: '',
      span: 'half',
      placeholder: '留空时根据风格自动设置',
      help: '实心风格默认使用深色文字；自定义浅色背景时可在此覆盖。',
    },
    {
      key: 'shape',
      label: '轮廓',
      type: 'enum',
      group: '外观',
      default: 'rounded',
      span: 'half',
      options: [...BUTTON_SHAPES],
    },
    {
      key: 'radius',
      label: '圆角 / 切角 (px)',
      type: 'range',
      group: '外观',
      default: 8,
      min: 0,
      max: 40,
      step: 1,
      span: 'half',
      when: { key: 'shape', in: ['rounded', 'cut'] },
      help: '圆角档是半径，切角档是斜边的边长。',
    },
    {
      key: 'borderWidth',
      label: '描边粗细 (px)',
      type: 'range',
      group: '外观',
      default: 1,
      min: 0,
      max: 4,
      step: 0.5,
      span: 'half',
    },
    {
      key: 'glow',
      label: '辉光',
      type: 'boolean',
      group: '外观',
      default: false,
      span: 'half',
      help: '在按钮外缘添加与主色一致的光晕。',
    },
    {
      key: 'glowRadius',
      label: '辉光半径 (px)',
      type: 'range',
      group: '外观',
      default: 12,
      min: 0,
      max: 40,
      step: 1,
      span: 'half',
      when: { key: 'glow', in: [true] },
    },
    {
      key: 'fontSize',
      label: '字号 (px)',
      type: 'range',
      group: '文字',
      default: 16,
      min: 8,
      max: 64,
      step: 1,
      span: 'half',
    },
    {
      key: 'fontWeight',
      label: '字重',
      type: 'range',
      group: '文字',
      default: 600,
      min: 100,
      max: 900,
      step: 100,
      span: 'half',
    },
    {
      key: 'letterSpacing',
      label: '字间距 (px)',
      type: 'range',
      group: '文字',
      default: 0,
      min: 0,
      max: 20,
      step: 0.5,
      span: 'half',
    },
    {
      key: 'iconSize',
      label: '图标字号 (px)',
      type: 'range',
      group: '文字',
      default: 0,
      min: 0,
      max: 64,
      step: 1,
      span: 'half',
      when: { key: 'icon', in: ENABLED_ICONS },
      help: '0 表示按文字字号的约 1.2 倍自动计算。',
    },
    {
      key: 'sizing',
      label: '尺寸',
      type: 'enum',
      group: '排布',
      default: 'fill',
      span: 'half',
      help: '「充满模块」使用节点矩形尺寸；「按内容」由文字与内边距决定尺寸。',
      options: [...BUTTON_SIZINGS],
    },
    {
      key: 'align',
      label: '水平位置',
      type: 'enum',
      group: '排布',
      default: 'center',
      span: 'half',
      when: { key: 'sizing', in: ['auto'] },
      options: [...BUTTON_ALIGNS],
    },
    {
      key: 'vAlign',
      label: '垂直位置',
      type: 'enum',
      group: '排布',
      default: 'center',
      span: 'half',
      when: { key: 'sizing', in: ['auto'] },
      options: [...BUTTON_VALIGNS],
    },
    {
      key: 'paddingX',
      label: '左右内边距 (px)',
      type: 'range',
      group: '排布',
      default: 20,
      min: 0,
      max: 64,
      step: 1,
      span: 'half',
      help: '仅显示图标时，四边统一使用「上下内边距」。',
    },
    {
      key: 'paddingY',
      label: '上下内边距 (px)',
      type: 'range',
      group: '排布',
      default: 10,
      min: 0,
      max: 48,
      step: 1,
      span: 'half',
      help: '「按内容」模式下决定按钮高度；「充满模块」模式下由模块矩形决定高度。',
    },
    {
      key: 'gap',
      label: '图标间距 (px)',
      type: 'range',
      group: '排布',
      default: 8,
      min: 0,
      max: 32,
      step: 1,
      span: 'half',
      when: { key: 'icon', in: ENABLED_ICONS },
    },
    {
      key: 'hover',
      label: '悬停反馈',
      type: 'enum',
      group: '动效',
      default: 'brighten',
      span: 'half',
      help: '触摸设备不触发悬停，建议同时配置按下反馈。',
      options: [...BUTTON_HOVERS],
    },
    {
      key: 'press',
      label: '按下反馈',
      type: 'enum',
      group: '动效',
      default: 'sink',
      span: 'half',
      help: '按下时的视觉反馈，适用于鼠标和触摸操作。',
      options: [...BUTTON_PRESSES],
    },
    {
      key: 'pulse',
      label: '呼吸提示',
      type: 'boolean',
      group: '动效',
      default: false,
      span: 'half',
      help: '以呼吸光环强调重要入口，建议单屏仅使用一处。',
    },
    {
      key: 'pulseDuration',
      label: '呼吸周期 (s)',
      type: 'range',
      group: '动效',
      default: 2,
      min: 0.6,
      max: 6,
      step: 0.2,
      span: 'half',
      when: { key: 'pulse', in: [true] },
    },
  ],
  preview: {
    config: { text: '进入详情', icon: 'arrow-right', iconPosition: 'right' },
  },
  component: () => import('./Component.vue'),
})
