/**
 * @fileoverview action-button —— 按钮控件：点一下上抛一次联动事件，显隐 / 弹窗 / 跨屏跳转
 * 都由大屏级联动规则决定，模块自己不认识任何一种动作。
 *
 * 为什么是一个独立模块而不是「文本块 + 卡片外观」：一个能点的东西必须**长得像能点**，
 * 而那要的是底色、描边、圆角、悬停与按下反馈一整套，不是把一段文字框起来。
 * 键盘可达、禁用语义与读屏角色也只有原生 `<button>` 才是白拿的。
 *
 * ⚠ 类型 id 是 `action-button` 而不是 `button`：守「运行时与编辑器里零模块类型
 * 字面量」的那道闸按已注册的 type 逐个 grep 源码，而模板里到处都是
 * `type="button"` / `role="button"`——叫 `button` 会让那道闸红在十几处无关的
 * 属性上，只能靠给闸门开豁免来消掉，而那正是它守的东西。
 */
import { defineModule } from '../../registry'
import {
  BUTTON_ALIGNS,
  BUTTON_HOVERS,
  BUTTON_ICONS,
  BUTTON_ICON_POSITIONS,
  BUTTON_PRESSES,
  BUTTON_SHAPES,
  BUTTON_SIZINGS,
  BUTTON_TONES,
  BUTTON_VALIGNS,
  BUTTON_VARIANTS,
} from './options'
import { BUTTON_TEXT_DEFAULT } from './look'

export default defineModule({
  type: 'action-button',
  description:
    '按钮控件：一个原生 `<button>`，点一下上抛一次联动事件；显隐、开弹窗、跨屏跳转、按值互斥切换全由大屏级联动规则决定，模块自己不认识任何一种动作。要一块明确「能点」的入口时用它；只想让一段文字或一张图可点，text-block 与 image-block 本身就整块可点，不必换成按钮。它没有绑定槽、不取数：「禁用」是常态置灰而不是随数据变，要按读数决定能不能点得靠联动规则控制显隐。配了「联动值」就随事件抛出它（「按值跳转大屏」「按值互斥切换」按它分流），留空则抛一个不带值的点击，显隐与弹窗类动作够用。⚠ 只配按钮不配联动规则的话，点了什么都不会发生，而两侧都不报错。',
  displayName: '按钮',
  category: '控件',
  icon: 'square-mouse-pointer',
  keywords: ['button', 'anniu', '按钮', '控件', '交互', '跳转', '入口'],
  // 自己画完整的按钮外观：再套一层卡片框就是两层边框，且圆角与切角对不齐
  chrome: 'bare',
  chromeConfigurable: false,
  defaultSize: { width: 180, height: 52, minWidth: 40, minHeight: 24 },
  // ⚠ 不开 hostClickable：按钮自己就是那个可点的东西，整块再兜底一次的话，
  // 按钮外的空白也能点，且同一次点击会上抛两遍（toggle 类动作当场自我抵消）
  emitsInteractions: true,
  bindings: [],
  configPresets: [
    {
      id: 'primary-action',
      label: '主行动',
      hint: '实心主色 + 圆角 + 辉光，一屏里最重要的那一个入口。',
      config: {
        variant: 'solid',
        tone: 'primary',
        shape: 'rounded',
        radius: 8,
        glow: true,
        glowRadius: 14,
        hover: 'brighten',
        press: 'sink',
      },
    },
    {
      id: 'hud-cut',
      label: '科技切角',
      hint: '斜切角 + 亮边斜面 + 悬停扫光，与页头、卡片的科技风一致。',
      config: {
        variant: 'hud',
        tone: 'primary',
        shape: 'cut',
        radius: 12,
        glow: false,
        hover: 'sweep',
        press: 'sink',
      },
    },
    {
      id: 'quiet-outline',
      label: '次要描边',
      hint: '中性描边胶囊，放在主行动旁边当「返回 / 取消」这类次要入口。',
      config: {
        variant: 'outline',
        tone: 'neutral',
        shape: 'pill',
        borderWidth: 1,
        glow: false,
        hover: 'glow',
        press: 'shrink',
      },
    },
  ],
  configSchema: [
    {
      key: 'text',
      label: '文案',
      type: 'string',
      group: '内容',
      default: BUTTON_TEXT_DEFAULT,
      span: 'full',
      help: '留空 = 只摆图标，按钮收成方形；读屏的名字改由「悬停提示」给。',
    },
    {
      key: 'subText',
      label: '副文案',
      type: 'string',
      group: '内容',
      default: '',
      span: 'full',
      placeholder: '留空则不画第二行',
      help: '主文案下面的一行小字，字号跟着主文案按比例走。',
    },
    {
      key: 'icon',
      label: '图标',
      type: 'enum',
      group: '内容',
      default: '',
      span: 'half',
      options: [...BUTTON_ICONS],
    },
    {
      key: 'iconPosition',
      label: '图标位置',
      type: 'enum',
      group: '内容',
      default: 'left',
      span: 'half',
      options: [...BUTTON_ICON_POSITIONS],
    },
    {
      key: 'hint',
      label: '悬停提示',
      type: 'string',
      group: '内容',
      default: '',
      span: 'full',
      placeholder: '留空则不提示',
      help: '鼠标停住时的一句话；没有文案的图标按钮拿它当读屏名称。',
    },
    {
      key: 'linkValue',
      label: '联动值',
      type: 'string',
      group: '行为',
      default: '',
      span: 'full',
      help: '点击时随事件上抛的值，「按值跳转大屏」「按值互斥切换」按它分流。留空 = 只抛一个不带值的点击，显示/隐藏/弹窗/单目标跳转都够用。',
    },
    {
      key: 'disabled',
      label: '禁用',
      type: 'boolean',
      group: '行为',
      default: false,
      span: 'half',
      help: '压暗并挡住点击。⚠ 它是常态置灰，不随数据变——要按数据决定能不能点，请用联动规则控制显隐。',
    },
    {
      key: 'variant',
      label: '风格',
      type: 'enum',
      group: '外观',
      default: 'solid',
      span: 'half',
      options: [...BUTTON_VARIANTS],
    },
    {
      key: 'tone',
      label: '语义色',
      type: 'enum',
      group: '外观',
      default: 'primary',
      span: 'half',
      help: '取主题里的语义色，换肤时整屏按钮一起变。',
      options: [...BUTTON_TONES],
    },
    {
      key: 'accent',
      label: '自定义主色',
      type: 'color',
      group: '外观',
      default: '',
      span: 'half',
      when: { key: 'tone', in: ['custom'] },
      placeholder: '留空 = 主题强调色',
    },
    {
      key: 'textColor',
      label: '文字色',
      type: 'color',
      group: '外观',
      default: '',
      span: 'half',
      placeholder: '留空 = 跟风格自动',
      help: '实心档默认压深色字。自定义主色配浅色时，用这里显式指定字色。',
    },
    {
      key: 'shape',
      label: '轮廓',
      type: 'enum',
      group: '外观',
      default: 'rounded',
      span: 'half',
      options: [...BUTTON_SHAPES],
    },
    {
      key: 'radius',
      label: '圆角 / 切角 (px)',
      type: 'range',
      group: '外观',
      default: 8,
      min: 0,
      max: 40,
      step: 1,
      span: 'half',
      when: { key: 'shape', in: ['rounded', 'cut'] },
      help: '圆角档是半径，切角档是斜边的边长。',
    },
    {
      key: 'borderWidth',
      label: '描边粗细 (px)',
      type: 'range',
      group: '外观',
      default: 1,
      min: 0,
      max: 4,
      step: 0.5,
      span: 'half',
    },
    {
      key: 'glow',
      label: '辉光',
      type: 'boolean',
      group: '外观',
      default: false,
      span: 'half',
      help: '按钮外一圈与主色同色的光晕。',
    },
    {
      key: 'glowRadius',
      label: '辉光半径 (px)',
      type: 'range',
      group: '外观',
      default: 12,
      min: 0,
      max: 40,
      step: 1,
      span: 'half',
      when: { key: 'glow', in: [true] },
    },
    {
      key: 'fontSize',
      label: '字号 (px)',
      type: 'range',
      group: '文字',
      default: 16,
      min: 8,
      max: 64,
      step: 1,
      span: 'half',
    },
    {
      key: 'fontWeight',
      label: '字重',
      type: 'range',
      group: '文字',
      default: 600,
      min: 100,
      max: 900,
      step: 100,
      span: 'half',
    },
    {
      key: 'letterSpacing',
      label: '字间距 (px)',
      type: 'range',
      group: '文字',
      default: 0,
      min: 0,
      max: 20,
      step: 0.5,
      span: 'half',
    },
    {
      key: 'iconSize',
      label: '图标字号 (px)',
      type: 'range',
      group: '文字',
      default: 0,
      min: 0,
      max: 64,
      step: 1,
      span: 'half',
      help: '0 = 跟着文字字号走（约 1.2 倍）。',
    },
    {
      key: 'sizing',
      label: '尺寸',
      type: 'enum',
      group: '排布',
      default: 'fill',
      span: 'half',
      help: '充满模块：按钮就是这个矩形，拖尺寸即改按钮大小。按内容：由字号与内边距撑开，再摆到矩形的某一处。',
      options: [...BUTTON_SIZINGS],
    },
    {
      key: 'align',
      label: '水平位置',
      type: 'enum',
      group: '排布',
      default: 'center',
      span: 'half',
      when: { key: 'sizing', in: ['auto'] },
      options: [...BUTTON_ALIGNS],
    },
    {
      key: 'vAlign',
      label: '垂直位置',
      type: 'enum',
      group: '排布',
      default: 'center',
      span: 'half',
      when: { key: 'sizing', in: ['auto'] },
      options: [...BUTTON_VALIGNS],
    },
    {
      key: 'paddingX',
      label: '左右内边距 (px)',
      type: 'range',
      group: '排布',
      default: 20,
      min: 0,
      max: 64,
      step: 1,
      span: 'half',
      help: '只摆图标不写文案时，四边一律取「上下内边距」，这一项不参与。',
    },
    {
      key: 'paddingY',
      label: '上下内边距 (px)',
      type: 'range',
      group: '排布',
      default: 10,
      min: 0,
      max: 48,
      step: 1,
      span: 'half',
      help: '「按内容」尺寸时它决定按钮高度；「充满模块」时高度由矩形定。',
    },
    {
      key: 'gap',
      label: '图标间距 (px)',
      type: 'range',
      group: '排布',
      default: 8,
      min: 0,
      max: 32,
      step: 1,
      span: 'half',
    },
    {
      key: 'hover',
      label: '悬停反馈',
      type: 'enum',
      group: '动效',
      default: 'brighten',
      span: 'half',
      help: '⚠ 触摸屏没有悬停：只靠这一档的大屏，在触摸屏上按下去是没有反馈的。',
      options: [...BUTTON_HOVERS],
    },
    {
      key: 'press',
      label: '按下反馈',
      type: 'enum',
      group: '动效',
      default: 'sink',
      span: 'half',
      help: '按住时的位移，触摸屏上唯一看得到的那一档反馈。',
      options: [...BUTTON_PRESSES],
    },
    {
      key: 'pulse',
      label: '呼吸提示',
      type: 'boolean',
      group: '动效',
      default: false,
      span: 'half',
      help: '常亮的一圈光环明暗呼吸，用来把视线引到某一个入口上。一屏里开一个就够。',
    },
    {
      key: 'pulseDuration',
      label: '呼吸周期 (s)',
      type: 'range',
      group: '动效',
      default: 2,
      min: 0.6,
      max: 6,
      step: 0.2,
      span: 'half',
      when: { key: 'pulse', in: [true] },
    },
  ],
  preview: {
    config: { text: '进入详情', icon: 'arrow-right', iconPosition: 'right' },
  },
  component: () => import('./Component.vue'),
})
