/**
 * @fileoverview 进度条部件：把这一格的读数画成一条占比。画法整件复用
 * `shared/MeterBar.vue`——info-list 的行里用的是同一份，不留第二套 CSS。
 *
 * ⚠ 算不出占比时整件不画——**绝不拿 0% 冒充「算不出来」**，那会让一条满量程的
 * 管道看着像空的。
 * ⚠ 一格里摆两条（占比 + 液位）就是摆两个这件、各自选槽，不需要第二个部件档。
 */
import { defineCardPart } from '../../../../cardParts/define'

export default defineCardPart({
  kind: 'meter',
  label: '进度条',
  icon: 'gauge',
  hint: '把读数画成一条占比。三种口径：直读占比槽、按量程折算、或占全卡之和的比。一格里摆两条就是摆两个这件、各自选槽。',
  slots: ['value', 'ratio', 'aux', 'aux2', 'extra1', 'extra2', 'extra3'],
  fields: [
    {
      key: 'source',
      label: '占比怎么来',
      type: 'enum',
      default: 'auto',
      span: 'half',
      help: '自动 = 接了「占比」槽就直读它、没接则按量程折算主读数（多数场合够用）。另三档是显式指定。',
      options: [
        { value: 'auto', label: '自动' },
        { value: 'ratio', label: '直读占比' },
        { value: 'range', label: '按量程折算' },
        { value: 'share', label: '占全卡之比' },
      ],
    },
    {
      key: 'slot',
      label: '读哪个槽',
      type: 'enum',
      default: 'value',
      span: 'half',
      help: '「自动」档不看这一项。其余三档：直读档读它取占比，量程与占全卡之比档读它取原值。',
      options: [
        { value: 'ratio', label: '占比' },
        { value: 'value', label: '主读数' },
        { value: 'aux', label: '副读数' },
        { value: 'aux2', label: '第三个数' },
        { value: 'extra1', label: '附加字段一' },
        { value: 'extra2', label: '附加字段二' },
        { value: 'extra3', label: '附加字段三' },
      ],
    },
    {
      key: 'look',
      label: '形态',
      type: 'enum',
      default: 'bar',
      span: 'half',
      help: '细条 = 小字 + 占比读数 + 轨道；粗轨道另带四根刻度与目标标记；分段格子按占比点亮前 N 格。',
      options: [
        { value: 'bar', label: '细条' },
        { value: 'track', label: '粗轨道' },
        { value: 'segments', label: '分段格子' },
      ],
    },
    {
      key: 'caption',
      label: '条前小字',
      type: 'string',
      default: '',
      span: 'half',
      placeholder: '如 占比 / 液位；留空则不画',
    },
    {
      key: 'min',
      label: '量程下限',
      type: 'number',
      default: 0,
      span: 'half',
      help: '只有「按量程折算」档用这两项。',
    },
    {
      key: 'max',
      label: '量程上限',
      type: 'number',
      default: 100,
      span: 'half',
    },
    {
      key: 'segments',
      label: '格数',
      type: 'range',
      default: 16,
      min: 4,
      max: 40,
      step: 1,
      span: 'half',
      when: { key: 'look', in: ['segments'] },
      help: '⚠ 一格代表 1/N：读数落在格与格之间时看不出来，要精确读数就同时开占比读数。',
    },
    {
      key: 'gap',
      label: '格间隙 (px)',
      type: 'range',
      default: 3,
      min: 0,
      max: 10,
      step: 1,
      span: 'half',
      when: { key: 'look', in: ['segments'] },
    },
    {
      key: 'height',
      label: '条高 (px)',
      type: 'range',
      default: 4,
      min: 2,
      max: 24,
      step: 1,
      span: 'half',
    },
    {
      key: 'width',
      label: '条宽 (px)',
      type: 'range',
      default: 0,
      min: 0,
      max: 400,
      step: 4,
      span: 'half',
      help: '0 = 铺满整格。',
    },
    {
      key: 'color',
      label: '颜色',
      type: 'color',
      default: '',
      span: 'half',
      placeholder: '留空 = 跟随强调色',
      help: '只填 var(--…) 引用，填死色值换肤时不跟着走。',
    },
    {
      key: 'glow',
      label: '辉光 (px)',
      type: 'range',
      default: 6,
      min: 0,
      max: 24,
      step: 1,
      span: 'half',
    },
    {
      key: 'showPercent',
      label: '显示占比',
      type: 'boolean',
      default: true,
      span: 'half',
      // ⚠ 占比读数不夹到 100：120% 正是要让人看见的那个异常
      help: '⚠ 条宽夹在 0–100% 之间，而这个读数不夹——120% 正是要让人看见的那个异常。',
    },
    {
      key: 'dot',
      label: '条前圆点',
      type: 'boolean',
      default: false,
      span: 'half',
    },
    {
      key: 'showTarget',
      label: '目标标记',
      type: 'boolean',
      default: false,
      span: 'half',
      help: '接了「对比值」槽才画，画在量程上的那个位置。只有粗轨道有。',
      when: { key: 'look', in: ['track'] },
    },
    {
      key: 'targetLabel',
      label: '目标标注',
      type: 'string',
      default: '目标 ',
      span: 'half',
      when: { key: 'showTarget', in: [true] },
    },
  ],
  component: () => import('./Meter.vue'),
})
