/**
 * @fileoverview text-block —— 装饰文本块：多行文字加一整套排版旋钮，不取任何数。
 * 大屏上的说明、单位、副标题这类固定文案都由它出。
 */
import { defineModule } from '../../registry'

export default defineModule({
  type: 'text-block',
  description:
    '静态文本模块，支持多行内容、字体、对齐、间距、溢出和辉光配置。适用于说明、标注、副标题、单位及页头页脚中的固定文字；实时读数应使用数据卡片类模块。模块不含数据绑定，配置联动规则后可作为整块点击入口。字间距 0 表示沿用默认值，不透明度采用 0–1 范围。',
  displayName: '文本块',
  category: '装饰',
  icon: 'type',
  keywords: ['text', 'wenben', '文本', '文字', '说明', '标注'],
  chrome: 'bare',
  hostClickable: true,
  contentKeys: ['title', 'text'],
  defaultSize: { width: 320, height: 72, minWidth: 40, minHeight: 24 },
  configSchema: [
    {
      key: 'title',
      label: '标题',
      type: 'string',
      group: '内容',
      default: '',
      span: 'full',
      placeholder: '留空则隐藏标题栏',
    },
    {
      key: 'text',
      label: '文字',
      type: 'textarea',
      group: '内容',
      default: '示例文本',
      span: 'full',
      help: '支持换行并保留行内连续空格。',
    },
    {
      key: 'fontSize',
      label: '字号 (px)',
      type: 'range',
      group: '文本',
      default: 16,
      min: 8,
      max: 120,
      step: 1,
      span: 'half',
    },
    {
      key: 'lineHeight',
      label: '行高',
      type: 'range',
      group: '文本',
      default: 1.4,
      min: 1,
      max: 3,
      step: 0.1,
      span: 'half',
    },
    {
      key: 'weight',
      label: '字重',
      type: 'range',
      group: '文本',
      default: 400,
      min: 100,
      max: 900,
      step: 100,
      span: 'half',
    },
    {
      key: 'letterSpacing',
      label: '字间距 (px)',
      type: 'range',
      group: '文本',
      default: 0,
      min: 0,
      max: 40,
      step: 0.5,
      span: 'half',
      // ⚠ 0 是哨兵不是零：它表示沿用样式表里的 0.02em（16px 字号下约 0.32px）。
      //   改成「0 = 真的 0」会把每一张没配过字距的存量大屏一起改窄，而两者的差
      //   小到看不出来——真正够不着的是负字距，那条路留给日后单开一个字段
      help: '0 表示沿用内置字间距（约为字号的 2%）；正数表示使用指定像素值。',
    },
    {
      key: 'fontFamily',
      label: '字体',
      type: 'enum',
      group: '文本',
      default: 'sans',
      span: 'half',
      help: '默认继承正文字体；中间两档取主题的标题体与等宽体，不引入额外字体资源。',
      options: [
        { value: 'sans', label: '默认（继承正文）' },
        { value: 'display', label: '标题体' },
        { value: 'mono', label: '等宽体' },
        { value: 'custom', label: '自定义' },
      ],
    },
    {
      key: 'fontFamilyCustom',
      label: '自定义字体',
      type: 'string',
      group: '文本',
      default: '',
      span: 'half',
      when: { key: 'fontFamily', in: ['custom'] },
      placeholder: '例如：Source Han Sans, sans-serif',
      help: '填写 CSS font-family；运行设备未安装对应字体时回退至系统字体，留空则继承正文。',
    },
    {
      key: 'color',
      label: '颜色',
      type: 'color',
      group: '文本',
      // 先看画布的「正文字色」，画布也没配才走主题色
      default: 'var(--card-text, var(--text-primary))',
      span: 'half',
    },
    {
      key: 'align',
      label: '水平对齐',
      type: 'enum',
      group: '文本',
      default: 'left',
      span: 'half',
      options: [
        { value: 'left', label: '左' },
        { value: 'center', label: '中' },
        { value: 'right', label: '右' },
      ],
    },
    {
      key: 'vAlign',
      label: '垂直对齐',
      type: 'enum',
      group: '文本',
      default: 'center',
      span: 'half',
      options: [
        { value: 'top', label: '上' },
        { value: 'center', label: '中' },
        { value: 'bottom', label: '下' },
      ],
    },
    {
      key: 'padding',
      label: '内边距 (px)',
      type: 'range',
      group: '外观',
      default: 8,
      min: 0,
      max: 48,
      step: 1,
      span: 'half',
    },
    {
      key: 'opacity',
      label: '不透明度',
      type: 'range',
      group: '外观',
      default: 1,
      min: 0,
      max: 1,
      step: 0.05,
      span: 'half',
      // ⚠ 量纲是 0–1，与图片块同名字段的 0–100 不是一回事：两边各自锁死，
      //   改任何一边的取值范围都会改存量大屏的渲染
      help: '取值 0–1，1 表示完全不透明；次要信息可适当降低。',
    },
    {
      key: 'background',
      label: '背景色',
      type: 'color',
      group: '外观',
      default: '',
      span: 'half',
      placeholder: '留空时透明',
    },
    {
      key: 'overflow',
      label: '溢出',
      type: 'enum',
      group: '外观',
      default: 'hidden',
      span: 'half',
      help: '设置文字超出模块矩形时的裁剪、滚动或逐行省略策略。',
      options: [
        { value: 'hidden', label: '裁剪' },
        { value: 'scroll', label: '滚动' },
        { value: 'ellipsis', label: '省略号' },
      ],
    },
    {
      key: 'glow',
      label: '辉光',
      type: 'boolean',
      group: '外观',
      default: false,
      span: 'half',
      help: '给文字加一层与文字同色的辉光。',
    },
    {
      key: 'glowRadius',
      label: '辉光半径 (px)',
      type: 'range',
      group: '外观',
      default: 10,
      min: 0,
      max: 40,
      step: 1,
      span: 'half',
      when: { key: 'glow', in: [true] },
      help: '设置辉光扩散半径；0 表示仅贴合文字轮廓。',
    },
  ],
  // 装饰文本不取数：要显示读数请用读数类模块，那边才有单位与阈值
  bindings: [],
  preview: { config: { text: '示例文本\n第二行' } },
  component: () => import('./Component.vue'),
})
