/**
 * @fileoverview text-block —— 装饰文本块：多行文字加一整套排版旋钮，不取任何数。
 * 大屏上的说明、单位、副标题这类固定文案都由它出。
 */
import { defineModule } from '../../registry'

export default defineModule({
  type: 'text-block',
  description:
    '装饰文本块：几行固定文案加一整套排版旋钮（字号、行高、字重、字间距、四档字体、水平/垂直对齐、内边距、不透明度、溢出处理、辉光）。大屏上的说明、标注、副标题、单位注解，以及页头/页脚里的大屏标题，都由它出。⚠ 它没有任何绑定槽、不取任何数：要显示读数请用 info-card 或 data-card，那边才有单位、小数位与阈值。整块可点，配了以它为源的联动规则时点它上抛一个不带值的 click。⚠ 「字间距」的 0 是哨兵不是零——表示沿用内置的约 0.02em；⚠ 「不透明度」量纲是 0–1，与 image-block 同名字段的 0–100 不是一回事。',
  displayName: '文本块',
  category: '装饰',
  icon: 'type',
  keywords: ['text', 'wenben', '文本', '文字', '说明', '标注'],
  chrome: 'bare',
  hostClickable: true,
  defaultSize: { width: 320, height: 72, minWidth: 40, minHeight: 24 },
  configSchema: [
    {
      key: 'title',
      label: '标题',
      type: 'string',
      group: '内容',
      default: '',
      span: 'full',
      placeholder: '留空则不画标题栏',
    },
    {
      key: 'text',
      label: '文字',
      type: 'textarea',
      group: '内容',
      default: '示例文本',
      span: 'full',
      help: '按行换行；行内连续空格原样保留，可以拿空格排版。',
    },
    {
      key: 'fontSize',
      label: '字号 (px)',
      type: 'range',
      group: '文本',
      default: 16,
      min: 8,
      max: 120,
      step: 1,
      span: 'half',
    },
    {
      key: 'lineHeight',
      label: '行高',
      type: 'range',
      group: '文本',
      default: 1.4,
      min: 1,
      max: 3,
      step: 0.1,
      span: 'half',
    },
    {
      key: 'weight',
      label: '字重',
      type: 'range',
      group: '文本',
      default: 400,
      min: 100,
      max: 900,
      step: 100,
      span: 'half',
    },
    {
      key: 'letterSpacing',
      label: '字间距 (px)',
      type: 'range',
      group: '文本',
      default: 0,
      min: 0,
      max: 40,
      step: 0.5,
      span: 'half',
      // ⚠ 0 是哨兵不是零：它表示沿用样式表里的 0.02em（16px 字号下约 0.32px）。
      //   改成「0 = 真的 0」会把每一张没配过字距的存量大屏一起改窄，而两者的差
      //   小到看不出来——真正够不着的是负字距，那条路留给日后单开一个字段
      help: '0 = 沿用内置字间距（约字号的 2%）；大于 0 时按 px 覆盖，填 0 不等于零字距。',
    },
    {
      key: 'fontFamily',
      label: '字体',
      type: 'enum',
      group: '文本',
      default: 'sans',
      span: 'half',
      help: '默认继承正文字体；中间两档取主题的标题体与等宽体，不引入额外字体资源。',
      options: [
        { value: 'sans', label: '默认（继承正文）' },
        { value: 'display', label: '标题体' },
        { value: 'mono', label: '等宽体' },
        { value: 'custom', label: '自定义' },
      ],
    },
    {
      key: 'fontFamilyCustom',
      label: '自定义字体',
      type: 'string',
      group: '文本',
      default: '',
      span: 'half',
      when: { key: 'fontFamily', in: ['custom'] },
      placeholder: '如 Source Han Sans, sans-serif',
      help: '直接写 CSS font-family 值；字体要在放大屏的机器上装好，装不到会回落系统字体。留空 = 继承正文。',
    },
    {
      key: 'color',
      label: '颜色',
      type: 'color',
      group: '文本',
      // 先看画布的「正文字色」，画布也没配才走主题色
      default: 'var(--card-text, var(--text-primary))',
      span: 'half',
    },
    {
      key: 'align',
      label: '水平对齐',
      type: 'enum',
      group: '文本',
      default: 'left',
      span: 'half',
      options: [
        { value: 'left', label: '左' },
        { value: 'center', label: '中' },
        { value: 'right', label: '右' },
      ],
    },
    {
      key: 'vAlign',
      label: '垂直对齐',
      type: 'enum',
      group: '文本',
      default: 'center',
      span: 'half',
      options: [
        { value: 'top', label: '上' },
        { value: 'center', label: '中' },
        { value: 'bottom', label: '下' },
      ],
    },
    {
      key: 'padding',
      label: '内边距 (px)',
      type: 'range',
      group: '外观',
      default: 8,
      min: 0,
      max: 48,
      step: 1,
      span: 'half',
    },
    {
      key: 'opacity',
      label: '不透明度',
      type: 'range',
      group: '外观',
      default: 1,
      min: 0,
      max: 1,
      step: 0.05,
      span: 'half',
      // ⚠ 量纲是 0–1，与图片块同名字段的 0–100 不是一回事：两边各自锁死，
      //   改任何一边的取值范围都会改存量大屏的渲染
      help: '取值 0–1（1 = 完全不透明）。调小可整体压暗，页头一类的次要信息常用 0.7。',
    },
    {
      key: 'background',
      label: '背景色',
      type: 'color',
      group: '外观',
      default: '',
      span: 'half',
      placeholder: '留空 = 透明',
    },
    {
      key: 'overflow',
      label: '溢出',
      type: 'enum',
      group: '外观',
      default: 'hidden',
      span: 'half',
      help: '文字超出模块矩形时：裁掉 / 可滚动 / 逐行省略号。',
      options: [
        { value: 'hidden', label: '裁剪' },
        { value: 'scroll', label: '滚动' },
        { value: 'ellipsis', label: '省略号' },
      ],
    },
    {
      key: 'glow',
      label: '辉光',
      type: 'boolean',
      group: '外观',
      default: false,
      span: 'half',
      help: '给文字加一层与文字同色的辉光。',
    },
    {
      key: 'glowRadius',
      label: '辉光半径 (px)',
      type: 'range',
      group: '外观',
      default: 10,
      min: 0,
      max: 40,
      step: 1,
      span: 'half',
      when: { key: 'glow', in: [true] },
      help: '辉光的扩散半径；0 = 只贴着笔画一圈。',
    },
  ],
  // 装饰文本不取数：要显示读数请用读数类模块，那边才有单位与阈值
  bindings: [],
  preview: { config: { text: '示例文本\n第二行' } },
  component: () => import('./Component.vue'),
})
